### ISSUE TITLE
Support for deleting notes from the notes list

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#10]
Presently, the only way to delete a note seems to be to enter the note and enter the tags management screen from within it. We discussed using an overflow menu within the note to surface that and some other options more directly but could you consider adding support for deleting notes from the notes list as well?

This could work the way that tag deletion works and bring up the option to delete a note when you long press on it but a much better implementation would be to let long pressing a note trigger a batch selection mode. The user could then pick as many notes as they want and the app bar would've changed tor reflect this mode and offer a delete option there along with maybe even a pin or archive option.

Here are a few examples of how this looks in different apps:

**Signal, showing you options to delete, archive and select all.**

![screenshot_20171010-070931](https://user-images.githubusercontent.com/20235646/31365810-39bd7d3c-ad8b-11e7-8f4d-cc1e00ac0fac.png)

**WhatsApp, showing options to pin/unpin, mute, archive with the delete option within the overflow menu.**

![screenshot_20171010-070946](https://user-images.githubusercontent.com/20235646/31365811-39f6676e-ad8b-11e7-9a9b-11d8f40acc6d.png)

**Tasks, letting you delete or copy.**

![screenshot_20171010-071003](https://user-images.githubusercontent.com/20235646/31365812-3a261360-ad8b-11e7-8acc-61c921e0df57.png)

**Phonograph, letting you do a whole host of things.**

![screenshot_20171010-071039](https://user-images.githubusercontent.com/20235646/31365813-3a5a6da4-ad8b-11e7-8b97-1c6b78d5af15.png)

I think exposing all 4 options from the tag management screen would be a nice implementation. Sorry if this issue seems to be asking too many things at once. Would you like me to break it into different issues?

**Comment by mobitar** [comment]
You know, I want to add long press to delete note, but reluctant to do so so late in the beta release stage. I've already established a baseline for what stability looks like across 20 or so betas, so I want to release with that confidence threshold I've built up.

Anyway, all that to say, long press will come in an immediate update after initial release.

**Comment by lokesh-krishna** [comment]
Yay! That does make sense.  
Is this app bar approach something you'd consider further down the line?

**Comment by mobitar** [comment]
That would be encroaching on complexity, but who knows. Really eager to begin exploring what extensions can be capable of on mobile.

**Comment by lokesh-krishna** [comment]
> That would be encroaching on complexity, but who knows.

But isn't that just standard Android behavior and that too involving only actions already available in the app?

> Really eager to begin exploring what extensions can be capable of on mobile.  
😁   
Markdown! Markdown! Markdown!

**Comment by mobitar** [comment]
We use React Native, so things will have to be done a little differently rather than using already available Android components. It's possible, but requires careful work.

**Comment by mobitar** [comment]
Done in 2.0.1
