### ISSUE TITLE
Startup shows nothing but a white screen before the app finally appears (Android)

### ISSUE THREAD

**Issue by Riotous** [standardnotes/mobile#100]
Can something be done to improve startup with the Android app? When tapping the app icon, I get a white screen that hangs for a little while before the app finally appears. Could you get rid of this white screen and improve startup time or at least add a splash screen?

**Comment by mobitar** [comment]
Is this on quit, or on resume from background? Do you have fingerprint or passcode lock enabled? And is the screen totally white, or is there any info at all on it?

**Comment by mobitar** [comment]
How many seconds would you say the tiny bit is?

**Comment by Riotous** [comment]
@mobitar less than a second to a second

**Comment by mobitar** [comment]
Improved in v3.
