### ISSUE TITLE
Running `react-native run-android` doesn't do anything

### ISSUE THREAD

**Issue by Arrow7000** [standardnotes/mobile#102]
I followed the instructions as described [in the readme](https://github.com/standardnotes/mobile#building-the-project). The first 2 steps run fine, but when I run `react-native run-android` I just get the message `react-native: command not found`.

Am I missing something?

I also tried adding `react-native run-android` as an npm script in case it was having trouble finding `react-native` in my node_modules but that didn't work either.

**Comment by mobitar** [comment]
You'd have to install react-native:

```
npm install -g react-native-cli
```

More here: https://facebook.github.io/react-native/docs/getting-started
