### ISSUE TITLE
Any plan on implementing widget for Android?

### ISSUE THREAD

**Issue by dsalaj** [standardnotes/mobile#103]
Are there plans to implement the widget feature for Android? My main use case for google keep is to have have the widget next to calendar widget so I have a good overview of everything on the single phone screen. Thanks for any information regarding this.

**Comment by mobitar** [comment]
This one is unlikely any time soon. Creating brand new additional areas of code makes it more difficult for us to maintain the core app, at least with our current level of resources.

**Comment by dsalaj** [comment]
@mobitar Thank you for the honest response. Does this imply that if someone would contribute by implementing this feature, it is unlikely to be accepted at this time due to the maintenance reasons?

**Comment by mobitar** [comment]
Yeah, exactly. We can't be sure that person would maintain that feature indefinitely, which means it's likely that it would lag behind in updates, thus causing even more discontent than not having it. Negative 1-star reviews would come pouring in :) (I've seen this happen before, so just have to be really careful.)

**Comment by dsalaj** [comment]
Thanks for the wise words. Best regards.

**Comment by mobitar** [comment]
Re-opening for visibility.
