### ISSUE TITLE
Android app crashes when clicking back while saving with external editor

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#104]
I use SN 2.3.10 on android 8.1.0,on a Nokia 8. 

Normally when I modify a note, for instance by adding a word / character, SN immediately saves it (showing Saving... in the top bar, until it's done saving). However, I have a couple of larger notes, and it takes a bit longer to save. When I click however the back button in the red top bar while it's saving, SN crashes completely.

I'm using plus editor, not sure if it also happens with plain editor (couldn't easily reproduce it with the plain editor)

**Comment by odyon01** [comment]
50k characters (57k incl html tags), 550 lines

**Comment by odyon01** [comment]
It's nearly 100% reproducible in the way I described (create a long note and click back right after you add an extra character and the app shows "Saving..."). But, indeed, I think it has something to do with timing: SN is saving the file and at that specific moment I click the back-button. The amount of time it takes to save the file is longer when a note is longer, thus I guess also the amount of time that I'm in a state where it can go wrong is longer, thus larger probability.

**Comment by odyon01** [comment]
I used a screen recorder to film it happening. How can I share this clip with you (15mb or so)?

**Comment by mobitar** [comment]
Awesome, you should be able to just drag and drop it here on GitHub. If you want to share it private, feel free to email it to me at mo@standardnotes.org.

**Comment by mobitar** [comment]
v3 makes a lot of improvements in this area. I haven't yet tested this bug explicitly, but let me know if you still notice it in this version.

**Comment by odyon01** [comment]
Unfortunately it still happens with 3.0.1. Do you have some debug mode I can enable for you to have more info or some stackdump? Could you reproduce it yourself?

**Comment by mobitar** [comment]
I'll have to give it a run. I just missed this issue when working through the 3.0 backlog unfortunately, so I'll have to account for it in a followup update.

**Comment by radko93** [comment]
The app should no longer crash in the latest version.
