### ISSUE TITLE
[iOS] Hyperlinks in extended editors open inside iFrame

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#109]
When clicking on a Hyperlink that's displayed inside an Extended Editor the link will open within the same iFrame. It's impossible to even go back to the editor. It should open the link in Safari (or optimally "In-app Safari View" with a Done button that takes one back to the editor).

Screenshot:
https://user.fm/files/v2-1d1ecbcc673b18781b39345725496524/IMG_1742.png

**Comment by mobitar** [comment]
This was fixed in a recent release.
