### ISSUE TITLE
[iOS] Home screen icon - Force touch menu

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#111]
A "force touch menu" would be extremely helpful on iOS. E.g. such as Safari or the built-in Apple Notes app have it:

http://s12572.pcdn.co/wp-content/uploads/2017/02/quickActions01.jpg

This would allow quickly adding or searching for notes. I suggest 2 menu items:

* Search
* New note

**Comment by mobitar** [comment]
There's a lot of under-the-hood architectural changes that would be required before we begin thinking about this. Some of it is underway, but still some time to go.

**Comment by christianhans** [comment]
Any reason why this was closed? Still would love to see this.
