### ISSUE TITLE
[Android] Pinned notes display as "Pinne"

### ISSUE THREAD

**Issue by wesaphzt** [standardnotes/mobile#114]
As per the title, any pinned notes on my Android app miss off the 'd' at the end of 'Pinned'.
Phone is a OnePlus 5T. A small issue, but an issue nonetheless.

**Comment by mobitar** [comment]
Strange. Can you attach a screenshot? Also, what version of the app?

**Comment by wesaphzt** [comment]
It's the latest version, 2.3.10.

![20130101_172906](https://user-images.githubusercontent.com/45947243/50222300-c6154480-038f-11e9-92c5-ff54bf3c5688.jpg)

Also noticed similar in the settings activity with "Op-" and "Secur-"
![20130101_172922](https://user-images.githubusercontent.com/45947243/50222345-e80ec700-038f-11e9-8361-42571ef569eb.jpg)

**Comment by mobitar** [comment]
This should be fixed in 3.0.0.
