### ISSUE TITLE
[Feature request] Reminder

### ISSUE THREAD

**Issue by hypery2k** [standardnotes/mobile#115]
I like standard notes: Therefore I would like to have reminders for notes. I could also fill a PR if anyone else would be also interested in this feature?

**Comment by mobitar** [comment]
Reminders are out of scope I'm afraid. We don't want to solve every problem (unless it can done with extensions). Focus is important for staying small and stable.

**Comment by hypery2k** [comment]
ok, i will try to solve it via extensions
