### ISSUE TITLE
Can you please clarify how encryption works on mobile?

### ISSUE THREAD

**Issue by manad777** [standardnotes/mobile#117]
I was reading https://listed.standardnotes.org/@sn/824/your-unencrypted-data-never-touches-a-hard-drive-with-device-storage-encryption , and I understand how encryption works for PCs.

For mobile, it says: (On iOS and Android, your keys are stored in your device’s secure keychain, so a local passcode serves more as a deterrent to unwanted physical access, compared to the web app, where a secure device keychain is not available.)

Just to make sure I'm understanding correctly, let's say someone has my device's PIN and can unlock it at will. They can theoretically decrypt my notes by reading the keys from the keychain and using them to decrypt the data? The local passcode or fingerprint lock is just to deter snooping from the average person?

**Comment by mobitar** [comment]
Keys stored in the keychain on iOS and Android are non-exportable. If someone can unlock your phone, it doesn't mean they can access your keys. On SN mobile, a passcode will be required before we attempt to access the keychain. Key security is largely handled by the OS on mobile, with little intervention from us. The local passcode isn't cosmetic though; it will encrypt your data if you're not signed into an account (if you're signed in, your account keys will be used instead). The fingerprint lock on the other hand has no cryptographic properties, and is a UI level deterrent. 

Android: https://developer.android.com/training/articles/keystore
iOS: https://developer.apple.com/documentation/security/keychain_services

**Comment by manad777** [comment]
Thank you for the reply!

**Comment by mobitar** [comment]
Update: on mobile, with the 3.0 release, the local passcode, if available, will now be used to encrypt the account keys before they are stored in the keychain. This means that even if the keychain values were able to be exposed by some means, they would be "double encrypted", and the values would be useless without knowledge of the local passcode.

**Comment by landry314** [comment]
the encryption system is a mess on this app. the design is confusing and obfuscated beyond what i can even figure out. i have posted about it a bunch with great suggestions but they seem to like to have a confusing system that barely anyone can figure out. beats me.

**Comment by JaspalSuri** [comment]
Hi @landry314, if you have any specific questions, we'd be happy to answer them. So far we haven't received a noticeable amount of reports by users being confused with how privileges/protections worked/work, so any additional feedback would be appreciated. 🙂 Please keep in mind that we still haven't redesigned the apps yet but are adding some of the features that we had originally planned after the redesign in advance.

**Comment by landry314** [comment]
im sorry i was rude. issues #338, #339, #340, #341 deal with clarity and security, all authored by me.
