### ISSUE TITLE
Simple Task Editor + themes = black text

### ISSUE THREAD

**Issue by mike-burns** [standardnotes/mobile#118]
Android  9 (5 Dec 2018), Google Pixel.

Combining the Simple Task Editor with any theme leads to a compose screen where the theme is applied but the text remains black. In the case of the Midnight theme this is nearly impossible to read; in the case of Solarized Dark it's very difficult to read.

(I say "nearly impossible" because Midnight's background is not #000 but the text is black. Have not confirmed but it must be #000.)

I have only seen this on the compose screen.

![screenshot_20190101-033839](https://user-images.githubusercontent.com/4550/50571393-05239c80-0d77-11e9-9972-e85d3a4ff380.png)

**Comment by mobitar** [comment]
I believe this is most likely a caching issue. All the themes were recently updated as a result of the 3.0 update on desktop/web. Can you try going in to the app settings from your main Android settings, and clearing the cache for the app? I think that should fix it.

**Comment by mike-burns** [comment]
Confirmed, that worked. Thank you!
