### ISSUE TITLE
Web editors don't work with Android <= 6

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#119]
Due to circumstances I’m using an old android phone (Moto g4, Android 5.1.1). Unfortunately I just discovered that when using Plus editor, notes are not saved. This caused me already to lose some text, which of course is the last thing I want to happen when using a note taking app.

I understand that it’s an old version of android, though still about 18% of android users is on lollipop. Starting the app (verifying keys after entering a passcode) also takes long (about 15sec), but this can just be due to the cpu (moto g4).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mobitar** [comment]
Are you able to replicate this issue at will? Definitely shouldn't be happening, even with an old phone. Can you describe what happens now when you use the Plus editor? When you make a change, does it say "Saving..." in the top bar, then "All changes saved"? If not, what do you see?

**Comment by odyon01** [comment]
I can easily reproduce it: I create a new note, enter a title, it now shows “All changes saved”. I then enable the plus editor and wait until it’s activated. Once it’s activated, it still shows “All changes saved”. I then type something, but it doesn’t show “Saving...”. I then close and reopen the note, and now it only shows “Compose” in the red title bar behind the back-button. When I switch back to plain editor, it immediately shows “Saving...” again.

I hope this clarified it a bit? I have another old phone lying around (android 5.0.2) and was able to reproduce it on that one as well.

**Comment by mobitar** [comment]
Do you have a newer Android phone you have access to, for the sake of testing? I'm curious if this is an account related issue or an OS issue. When was your account created? It's possible that the extensions you have installed may be super cached or something. Via the desktop/web app, can you try uninstalling the editors you have installed, then re-install, then trying again on Android?

**Comment by odyon01** [comment]
Unfortunately, I don't have a newer phone lying around (as my Nokia8 is being repaired). I tried uninstalling the editors, and re-installing them, and the issue still persists. My account was created about half a year ago.

Is it correct that after testing this, I now have to go through each note, and re-enable the plus editor? Or is there an easier way to do this all at once? Because with 100+ plus-notes, it's a bit annoying and I didn't realise I had to do this, when doing the uninstall-reinstall-test...

**Comment by mobitar** [comment]
Oh, very sorry about that. Failed to mention that aspect. Yes, you would have to re-assign each note. You can also set the Plus editor to default. Although that won't work on mobile. Or, if you have a backup file from before you did the change, you can import just the Plus editor from that backup file and it will restore all those associations. You can find backups via the top-level Backups menu. By default they're stored in your home directory. Find one from a recent date before the change. Then use the Batch Manager extension's Backup Explorer feature to find the Plus editor and import only that one. (Uninstall the current Plus editor before you do this to avoid confusion).

**Comment by mobitar** [comment]
You're right, editors do not function properly with Android version <= 6. The latest update will display an alert to users trying to operate editors in this environment.
