### ISSUE TITLE
Replace checkboxes with highlighting in the sidebar

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#12]
The app presently uses checkboxes in the sidebar when the items in it can only be selected singly.

An alternative could be to use highlights for both, the presently selected sort mode and the presently selected tag filter. The highlight would use a lighter variant of the app's primary color and the text within could be highlighted in the primary color for a much more pleasant experience.

Here is an example of what it looks like on Simplenote:

![unnamed](https://user-images.githubusercontent.com/20235646/31847091-4b722bbc-b633-11e7-8229-ac4acc026dd7.png)

**Comment by mobitar** [comment]
Yup, was planning on doing this in a future update.
