### ISSUE TITLE
[Android] "fling" scrolling of note list fails after opening a note

### ISSUE THREAD

**Issue by quartertone** [standardnotes/mobile#121]
Normal/expected behavior is that the list of notes would continue to scroll after "flinging" the list up/down. This happens as expected at first. But I have noticed that (consistently) after I open a note and then exit into the note list, the list no longer scrolls after flinging - rather it scrolls only until the finger is lifted off the screen. Sometimes this also happens right after the note list is fully loaded. I created a video to show the problem.

(video upload not supported in github, so here's the video file)
https://web.tresorit.com/l#GvWijQPA_2Ulaou3jjWg2Q

Android SN app version 2.3.10, Oneplus 5T with Android 8.1.0

**Comment by mobitar** [comment]
Thanks for the video, that's very helpful! v3 of the mobile app is getting ready for a beta release. It features a redesign in many places. I've been playing with it on Android for the past few days and have not seen this issue. Please sign up for the beta, and when it's released, let me know if you continue to notice it there.

Beta: https://play.google.com/apps/testing/com.standardnotes

**Comment by SiGamma** [comment]
Slightly related, any chance for an iOS (TestFlight) beta? I would love to join!

**Comment by mobitar** [comment]
I haven't been able to replicate this in v3. Please re-open if you continue to see this.
