### ISSUE TITLE
[3.0.0-Beta3] No way to permanently delete notes on mobile?

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#124]
On Desktop I can both permanently delete notes from Trash and also empty the entire Trash. On Mobile I would at least like to be able to permanently delete notes by long pressing inside the Trash view.

**Comment by mobitar** [comment]
I have a note to add it to the long press menu. Currently you have to open the note, then the note side menu, to delete or empty the trash.

**Comment by mobitar** [comment]
Option to permanently delete has been added to action sheet in 3.0.0.
