### ISSUE TITLE
[iOS] [3.0.0-Beta3] Sidebar section collapse state doesn't persist when closing the app

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#125]
Let's say I toggle for example the Editor section to hide it in the right side bar. It will stay hidden until I (force) close the App. I would like this to persist even when closing the App.

**Comment by mobitar** [comment]
The Editor and Themes sections will be collapsed by default, so when you restart the app, they should be hidden. Noted about custom persistence.
