### ISSUE TITLE
Backup to local file does not work on Android

### ISSUE THREAD

**Issue by pioneer42** [standardnotes/mobile#126]
On Samsung Galaxy A3 running Android Oreo 8.0.0 and Standard Notes 2.3.0, the Export Data - Encrypted option does not work as expected. It will only give an option to send the encrypted backup as e-mail, but no option to save the encrypted backup as a file for instance to the memory card. Standard Notes is setup to use a local passcode (not logged in to your servers).

**Comment by mobitar** [comment]
The new v3 beta will now save the backup to disk instead of emailing. You can try it here: https://github.com/standardnotes/forum/issues/425

**Comment by mobitar** [comment]
3.0.0 has been released with this feature.
