### ISSUE TITLE
Plus editor not available when in airplane mode? 

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#127]
When I'm in airplane mode, I can't view the notes that I made using plus editor on android (except when I switch to plain editor which of course is not usable).

**Comment by mobitar** [comment]
This is correct, as Extended editors are not currently available offline on mobile. Still have it on my long-term to do to investigate feasibility of this.

**Comment by odyon01** [comment]
Hm, I consider this a bit a miss. One of the reasons for me switching to SN is to always have my notes with me, all the time, and available to access. But this means you exclude everyone who also work offline (in an airplane for instance)? Or force them to go for plain editor?

**Comment by mobitar** [comment]
Yeah, you'd just have to switch to the plain editor. In a future update, instead of displaying a full screen "unable to load editor", we want to have just a small bar at the top that says "Editors not available offline", and display the plain editor under, just so that you don't have to spend time switching.

**Comment by thomaseizinger** [comment]
Why do the editors have to be loaded every time? Couldn't they be cached locally? TBH, I find it very annoying because on mobile, I have a ~1 second delay before I can use my notes as the editor has to load EVERY time.

**Comment by mobitar** [comment]
They are cached, but not directly by us. Handled by system. The first time you access an editor, it would take about 3-5 seconds to load. Subsequent times take about 1s.

**Comment by sentriz** [comment]
I think offline/cached editors would be a very nice feature - esp. now that I'm using tokenvault - where with the current situation I can't get my tokens on my phone without internet
