### ISSUE TITLE
Web editors do not create extra padding to avoid keyboard

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#128]
Since a few weeks I own a ipad, running latest ios, and I noticed an issue with both the ios app as well as the Web-app (via safari). When I try to type something, the keyboard may sometimes be over the text I'm trying trying write, or, the plus-editor-menu bar is scrolled to the top of the screen.

Basically what happens, when folding out the keyboard in landscape / horizontal mode, it's not the that text area where you write the note is resized to less high, but it stays the same height and moves up, so that top of my note, including the plus menu bar dissappears.

I'll try to make some screenshots later.

**Comment by mobitar** [comment]
Good point, I can replicate this using the Extended editors but not the plain editor. This one sounds tricky in theory but I'll have a look.

**Comment by mobitar** [comment]
This has been fixed in a recent release.
