### ISSUE TITLE
Note menu empty after pressing the tag button

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#129]
On 3.0.0.beta4 for android (9), when I have a note open, I Swipe to the right/press the right menu button, press the round "add tag" button, and then press the "close new tag screen" button, I sometimes end up with a blank sidebar menu. Closing it and opening it resolves it. 

 ![](https://i.imgur.com/isG38L7.png)

**Comment by mobitar** [comment]
Can confirm this behavior, thanks for the heads up.

**Comment by mobitar** [comment]
Should be fixed in 3.0.0 release.
