### ISSUE TITLE
On Android, pasting in or adding new text with keyboard open doesn't expand scrollable area.

### ISSUE THREAD

**Issue by quartertone** [standardnotes/mobile#130]
Bug:
Open long note, paste long thing at the end. Trying to scroll up to the top doesn't go to the top while the keyboard is open. Closing the keyboard and opening it again (going back in to edit) corrects this bug.

Another (related?) bug:
When editing a long note, typing or pasting at the end of the note (after having scrolled to the bottom), then returning to the note list causes the list to appear scrolled down about as much as was scrolled down in the note.
Same thing (aberrant scroll position) happens in the tag list as well.

**Comment by mobitar** [comment]
Yeah, this is a tricky issue. I noticed this late in my testing as well. Haven't found a good solution yet. Will need to experiment with it more.

**Comment by radko93** [comment]
Thank you for the report, this is fixed in the latest version.
