### ISSUE TITLE
[Android 3.0.0] Keyboard does not pop up in existing notes' body

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/mobile#132]
Hi there,

I love the v3 look! Unfortunately for me the keyboard does not pop up when I'm trying to edit an existing note. I can only edit the title, but not the body. For a new note it works without issues. This is just with the plain editor.

I'm running LineageOS on Android 7.1.2. There were no issues before the upgrade.

Happy to provide any other info. Thanks!

**Comment by mobitar** [comment]
Hey @ddddavidmartin, sorry about that. 3.0.1 was just pushed with the fix. Please update to that when it is available within the hour.

**Comment by ddddavidmartin** [comment]
> sorry about that

No worries at all! It works fine again with the latest update.
