### ISSUE TITLE
iOS SwiftKey keyboard not working smoothly 

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#14]
When using a 3rd party keyboard like SwiftKey, input becomes laggy/misses words.

**Comment by AdamVig** [comment]
This happens to me every time I use the app:
1. Type with SwiftKey
2. Input gets laggy
3. Cursor jumps down several lines (so I move it back)
4. Repeat a couple times
5. SwiftKey apparently crashes, iOS default keyboard takes over

I can help test a beta version that fixes this problem, let me know.

**Comment by mobitar** [comment]
Hey Adam, sorry about that. Still don't have any leads into why SwiftKey is causing this issue. I have it down to spend more time investigating but not sure when I'll get to it.

**Comment by mobitar** [comment]
I'm hearing that v2.2.3 of the SwiftKey app has resolved this issue.

**Comment by AdamVig** [comment]
Tested on iOS 11.2.2 with SwiftKey 2.2.3 and the issue still occurs.

I wrote about two sentences and saw a minor blip, but the keyboard did not crash. Then I wrote another two sentences and it crashed as described above.

**Comment by mobitar** [comment]
Hmm..and I'm assuming you restarted SN after you updated SwiftKey?

**Comment by AdamVig** [comment]
I did not do that in my first test, but I just tested again after restarting Standard Notes and the keyboard crashed after I wrote about a sentence and a half.

**Comment by AdamVig** [comment]
Thank you, this fixes the problem!

Hopefully this bug report helps you hone in on the performance bottleneck that is causing the problem.

**Comment by mobitar** [comment]
Yup, definitely useful. Just unsure of how much can really be done. Encryption does indeed add a few milliseconds of latency. Perhaps there can be an option in the settings to save less often than every few keystrokes..

**Comment by AdamVig** [comment]
Right. I have often wondered why the app saves so aggressively. I would not mind it saving every five seconds or so.

**Comment by mobitar** [comment]
Turns out, this had nothing to do with the encryption and everything to do with the "Saving..." / "All changes saved" subtitle that appears in the nav bar. This has been fixed, and will be deployed in the 2.2 update some time this month :)

**Comment by AdamVig** [comment]
@mobitar I was just looking at the diff myself and was also surprised. Good find! I look forward to being able to use SwiftKey without any lag. Thanks for taking care of this.
