### ISSUE TITLE
feature request: share text to app to add note

### ISSUE THREAD

**Issue by garywill** [standardnotes/mobile#140]
Hello developers,
Could you please add feature to share any text to this app to add new note?

**Comment by mobitar** [comment]
This is something that's currently in consideration and might be added to a future release. No date expectation yet.

**Comment by garywill** [comment]
Hi, is this being planned?

**Comment by stefan-yas** [comment]
Yes. Most of the team is busy with working on the current roadmap features, but this is one of the features that we are still considering implementing, so sorry we can't give you a more clear timeline on when it's going to be implemented.
