### ISSUE TITLE
[feature request] a button to scroll down to the end of a note

### ISSUE THREAD

**Issue by TimelyLog** [standardnotes/mobile#143]
I am on Android and have really long notes which I visit frequently. It takes me almost 5 seconds and gymnastic activity in my fingers to reach the bottom of the note.

I know that on some websites there are buttons to scroll back to the top when you reach the bottom, would it be possible for something similar (just in reverse) to show up when you tap on a note?

**Comment by mobitar** [comment]
I've never seen any app do this to be honest, on iOS at least. It's completely unheard of. If you have examples on Android, please share.

**Comment by TimelyLog** [comment]
Honestly I have rarely seen an app do this either. Especially since a 'back to top' button would be redundant on iOS because you could just tap on the notification bar. Such a button is known to me mostly from newspaper websites but I was also able to find one in the app of the Spiegel newspaper (which is probably just their website in an app). [Here](http://imgur.com/a/vkSMWuB) are two screenshots.
For the standardnotes app such a button would be quite useful to me, just in reverse. I could also imagine an option to get straight to the bottom of a note if you tap on it.

**Comment by mobitar** [comment]
I believe that if you tap into a note to begin editing, it would scroll it to the bottom, no? At which point you can dismiss the keyboard.

**Comment by TimelyLog** [comment]
No, right now it does not scroll to the bottom. I think it does on the desktop version but not on Android. [Here](http://imgur.com/a/S7ze3Lm) is a quick demonstration. I am not quite sure what you mean by the point I can dismiss the keyboard, but having an option to get right to the bottom of a note when tapping into one would be great.

**Comment by mobitar** [comment]
What would happen if right after you open the note, and without doing any scrolling, you tap on the content to bring the keyboard up—does it scroll to the end, and place the cursor at the end? Or does it place the cursor where you tapped?

**Comment by TimelyLog** [comment]
It places the cursor where I tapped.

**Comment by mobitar** [comment]
Got it, thanks. To be honest I don't believe we'd add a dedicated button in the UI for this. But perhaps some kind of invisible shortcut could be imaginable.

**Comment by TimelyLog** [comment]
It's not so much about the button, it was just the first thing which came to my mind. I believe being able to scroll down without a button seems even better and fits the minimalistic style. Thank you for taking your time reading my suggestion, I love SN and hope it will continue to prosper in the future!

**Comment by mobitar** [comment]
Thank you @TimelyLog!
