### ISSUE TITLE
[iOS] Paste doesn’t work in Extended Editors

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#145]

**Comment by mobitar** [comment]
Can't replicate. Which editors, and which version of the app?

**Comment by christianhans** [comment]
3.0.5

All editors, for example Advanced Markdown Editor. Would a screen recording help?

Best
Christian

**Comment by mobitar** [comment]
Yes please. I tested on Advanced MD Editor and Simple Task Editor for the record and it worked just fine.

**Comment by christianhans** [comment]
Ah, so when you I press and hold long time the Paste toolbar appears. I was trying a short tap which other Apps support.

Best
Christian

**Comment by mobitar** [comment]
Hmm I suppose that's true. Might be webview related. On the Simple Task Editor task input field, short tap works. On the textarea task fields, short taps don't.

**Comment by christianhans** [comment]
Not sure if this issue should be closed. It’s almost impossible to paste text in extended editors on mobile (try pasting text next to existing text, it will just select the existing text when long pressing and then overwrite the existing text when pasting). Other HTML based editors on iOS don’t show this issue so there must be something going on with the Standard Notes app.

**Comment by mobitar** [comment]
I don't anticipate much we can do here. It's a webview that loads a URL, with notoriously few points of customization.
