### ISSUE TITLE
[IOS] Unlocking by fingerprint is still a pain

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/mobile#147]
Unlocking the SN IOS app is still a pain to use.

Everytime i start SN, the IOS fingerprint popup is shown and detect my fingerprint,
but SN fails to unlock and you have to hit the "unlock" button and repeat.

So you *MUST* release the finger from the sensor *BEFORE* starting SN and put it again on the sensor. This is the only way SN unlocks correctly.

On every IOS app, that support unlock by fingerprint, that I ever used, doesn't behave like that.
Normaly you can start all apps by having a finger on the sensor, before starting the app.
Please look at this. It's very anoying.

**Comment by mobitar** [comment]
What version of the app is this?

**Comment by MustachedMario** [comment]
iOS Version 3.0.5. (Latest one in AppStore)

**Comment by mobitar** [comment]
I've tested with Face ID, but it should be the same flow. However I don't get the same result. What is your timing for Fingerprint ("Immediately" or "On Quit"), and do you also have a local passcode set up? If you can capture a screen recording that might be very helpful.

**Comment by MustachedMario** [comment]
- Local passcode is disabled
- Timing is set to "on quit", but tested it also with "immediately", same result.
- I try to attach a screen capture later this day... hold on..

**Comment by MustachedMario** [comment]
I managed to create 2 captures.
- One video showing unlocking by fingerprint when it is requested.
- Other video is shown unlocking SN by fingerprint when the finger is already on the sensor before app start

hope that helps...

[SN-IOS-Fingerprint-Issue.zip](https://github.com/standardnotes/mobile/files/3117562/SN-IOS-Fingerprint-Issue.zip)

**Comment by mobitar** [comment]
Hmm interesting. So simply having your finger on the sensor changes its behavior? That's very unusual for iOS. The app doesn't typically read the sensor until the dialog comes up. I'll need to test this with a fingerprint device when I get the chance. If anyone else can confirm this behavior, please let me know.

**Comment by MustachedMario** [comment]
FYI. The latest version 3.0.8 (iOS) works like it should.

Unlocking on app start working, even the finger is on the sensor before app start.
So technical, it works like should, but i think it was a side effect of other changes, because it still looks like the second video, where all ends in the blue "unlock" button, but a second later, unlocking is done.

**Comment by mobitar** [comment]
The latest iOS release did make some changes to this area, in particular, it was an update in response to the issue where when you closed the app with Fingerprint set to Immediate, it would quickly flash the fingerprint alert then close it.

So is this issue fixed and good to close then?

**Comment by MustachedMario** [comment]
I think we can close this issue.
