### ISSUE TITLE
[iOS] Cancel search button disappears

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#148]
Under certain circumstances the button to cancel the current search disappears:

![sn_bug](https://user-images.githubusercontent.com/355541/56862476-605a4a00-6979-11e9-92fd-14233fe8045f.png)

This occurred a couple of times already but I haven't yet found a way to safely reproduce this.

**Comment by mobitar** [comment]
Yeah, have seen this one myself as well. Will need to investigate.

**Comment by radko93** [comment]
This should no longer happen in the latest version as the search bar is different.
