### ISSUE TITLE
Suggestions regarding the long press menu

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#15]
Just collecting my suggestions here, in case you're interested in any of them.

- I think the appearance could be improved by using [Material icons](https://material.io/icons/). All the actions currently exposed in the menu have icons available for them. This could be complemented by aligning the text to the left with the icons to their left. 
- The cancel button could be dropped entirely since tapping anywhere out of the menu accomplishes that anyway. 
- The delete button along with its icon could be colored red instead for better visual distinction.
- The note title could be added to the same box as the options but centered, unlike the option which would now be left aligned.

**Comment by mobitar** [comment]
Thanks Lokesh, this is good feedback. Hope to get to it soon.
