### ISSUE TITLE
simple task editor text is small

### ISSUE THREAD

**Issue by sentriz** [standardnotes/mobile#156]
howdy
when I open the task editor, the inital text is very small. I can zoom in with my fingers, but it would be nice if it was already a good size
thank you

preview
![](https://i.imgur.com/gDdAtq6.png)

**Comment by mobitar** [comment]
Hmm that's strange. Is it only this editor, or all editors? Can you try going into your Android settings and find the Storage settings for S. Notes, then Clear Cache?

**Comment by sentriz** [comment]
@mobitar it's for all editors - I should have mentioned. I'll clear the cache and report back
cheers

**Comment by sentriz** [comment]
thank fixed it :) thank you for the help

**Comment by mobitar** [comment]
Ok great!

**Comment by kylejbrk** [comment]
I'm having this issue and clearing the cache did not fix it. Happens on almost all the text editors. Any idea how to fix it?

**Comment by JaspalSuri** [comment]
Can you try signing out and back in to see if that helps? If not, please let us know!

**Comment by kylejbrk** [comment]
@JaspalSuri Tried that as well reinstalling the app. Also should mention I am self hosting the latest release from Github. Here is my index.html:

```
{
    "area": "editor-editor",
    "content_type": "SN|Component",
    "description": "A great way to manage short-term and long-term to-do's. You can mark tasks as completed, change their order, and edit the text naturally in place.",
    "flags": [],
    "identifier": "org.standardnotes.simple-task-editor",
    "marketing_url": "https://standardnotes.org/extensions/simple-task-editor",
    "name": "Simple Task Editor",
    "thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/task-editor.jpg",
    "version": "1.3.5",
    "download_url": "https://api.github.com/repos/sn-extensions/simple-task-editor/zipball/1.3.5",
    "url": "https://kylejbrk.github.io/standard-notes-open-extended/simple-task-editor/1.3.5/dist/index.html",
    "latest_url": "https://kylejbrk.github.io/standard-notes-open-extended/simple-task-editor/index.json"
}
```

**Comment by JaspalSuri** [comment]
Hmm, I'm sorry to hear that. @radko93 & @johnny243, can you look into this?

**Comment by radko93** [comment]
I've tested the editor from `https://kylejbrk.github.io/standard-notes-open-extended/simple-task-editor/index.json` and it's loading as very small indeed. But regular Task Editor works fine so I'm not sure what's going on yet.

**Comment by kylejbrk** [comment]
Glad to know it's not just me. This happens with some of the other editors like the Markdown ones as well.

**Comment by kylejbrk** [comment]
Any updates? Should I open a new issue?

**Comment by mobitar** [comment]
You need to add this to your HTML:

```
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
```
