### ISSUE TITLE
Android App Name

### ISSUE THREAD

**Issue by realmain** [standardnotes/mobile#16]
**Ver:** 2.0.2

When installed, the app is installed to **com.standardnotes** but the app itself is just called **Notes**, which sounds extremely generic when looking through my installed app list. Is it meant to be like this? It'd be better if it was actually called **Standard Notes**.

**Comment by mobitar** [comment]
This was a tricky one. "Standard Notes" is kind of long to be below an icon. So the choice was either between "S. Notes" and "Notes". On iOS, it's S. Notes, and on Android it's kept as Notes since that's what V1 had.

**Comment by realmain** [comment]
To keep it the same on mobile, we should probably call it **S. Notes** on Android too :)

Anything is better than just **Notes** haha.

**Comment by mobitar** [comment]
Yeah, you're right. I'll try to make this change for the next release. I guarantee you though we're gonna be seeing a new GitHub issue that says "Please change name back to Notes" ;)

**Comment by b2m9** [comment]
Correct me if I'm wrong, but isn't "S Notes" the name of Samsung's notes app?

(Personally, I don't find "Notes" too generic)

**Comment by mobitar** [comment]
Is it? I didn't know Samsungs came with a default notes app. Does anyone have screenshots of that?

**Comment by daylightbrightledlight** [comment]
I think the dot in the app name for iOS makes it look ugly. I would prefer something like "SNotes" instead.
