### ISSUE TITLE
Pasting text not working on Android anymore

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/mobile#162]
Good day,

I am not sure since when, but pasting text is not working on my Android version of Standard Notes. Pressing and holding the cursor doesn't do anything. Is it something with my setup or a bug with Standard Notes?

Standard Notes: 3.0.10

Happy to provide any further details as necessary.

Thanks!

**Comment by mobitar** [comment]
Which editor is this with—plain, or another editor?

**Comment by ddddavidmartin** [comment]
I'm using the Plain Editor and the Simple Task Editor and pasting doesn't work with either of them.

**Comment by mobitar** [comment]
That's surprising. We haven't really done anything new in this area. No other reports besides this one either. Can you copy inside the plain editor? Then try pasting?

**Comment by ddddavidmartin** [comment]
So, it is working again now. I hate to say it, but I solved it by reinstalling the app. I didn't even have to log in again as all the data was still there. But pasting is working again.

> Can you copy inside the plain editor? Then try pasting?

I didn't get to try this, sorry. It wasn't just a one off though. I wasn't able to paste for a couple of weeks I reckon. And I would forget about until I ran into it again every now and then.

**Comment by mobitar** [comment]
Very strange! Well, glad you got it working.

Regarding the data still being there after uninstall, you can change this via Android system Settings > System > Backup > App data.

**Comment by ddddavidmartin** [comment]
> Regarding the data still being there after uninstall, you can change this via Android system Settings > System > Backup > App data.

Good to know, thanks! Though I was not really concerned about this, but incredulous that re-installing solved the problem whilst seemingly not changing anything at all.

I'll close this issue as the problem is gone.
