### ISSUE TITLE
Hermes support

### ISSUE THREAD

**Issue by starlesschris** [standardnotes/mobile#169]
Hey,
Facebook just released / open sourced [Hermes](https://github.com/facebook/hermes),

> [...] a small and lightweight JavaScript engine optimized for running React Native on Android.

Enabling it seems to be quite easy: [How to](https://facebook.github.io/react-native/docs/hermes)

Are there plans or thoughts on using it? It should

> {...] result in improved start-up time, decreased memory usage and smaller app size

**Comment by mobitar** [comment]
Hmm interesting. Thanks for the heads up. We'd need to update our React Native version. Will keep this in mind for the next big update.

**Comment by radko93** [comment]
Hey, we enabled Hermes and it will be available in the new 3.5 version.
