### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by realmain** [standardnotes/mobile#17]
I was curious if an F-Droid release is being considered as that is the only app store I really use on my phone.

**Comment by mobitar** [comment]
It is being considered, but it definitely takes some effort to get that working. I got it started here, need to revisit it: https://gitlab.com/fdroid/rfp/issues/379

**Comment by Lionirdeadman** [comment]
Any news about this? @mobitar

**Comment by mobitar** [comment]
No sorry. Building for F-Droid is just too time consuming and I couldn't get it to work. If anyone wants to take a stab at it, that would be mighty helpful.

**Comment by mobitar** [comment]
We're making some progress on this over at https://gitlab.com/fdroid/rfp/issues/379
