### ISSUE TITLE
iOS 13: Scrollbar moves to left side

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#174]
![Screenshot 2019-08-17 at 13 59 32](https://user-images.githubusercontent.com/355541/63215623-6fffc900-c0f7-11e9-890a-8cfbb2a944c8.png)

![Screenshot 2019-08-17 at 13 57 23](https://user-images.githubusercontent.com/355541/63215626-768e4080-c0f7-11e9-9077-d66e0555a217.png)

**Comment by christianhans** [comment]
Doesn’t occur at all times. Noticed it with Plain and Simple Task Editor so far. With Simple Task Editor the scrollbar hovers over the check boxes.

**Comment by christianhans** [comment]
Does the App need to be recompiled with the latest iOS SDK? This issue is becoming a little bit cumbersome with the stable version of iOS 13 being out. Simple Task Editor is uns able due to the scroll bar hovering over checkboxes.

**Comment by mobitar** [comment]
Interesting, can replicate. Will explore this.
