### ISSUE TITLE
Restore from trash menu option looks like inactive menu heading

### ISSUE THREAD

**Issue by da2x** [standardnotes/mobile#175]
The “Restore [from trash]” menu option is styled the same way as the accordion menu groupings (which have no indicator to suggest they’re accordions, by the by.) I glanced over this menu several times before spotting the inconsistently styled Restore option. It should be set in black with an icon on the right like the other options in the same menu.

See this [screenshot of the menu](https://user-images.githubusercontent.com/1102886/63442067-bb391500-c432-11e9-9715-1773f80b4029.jpg).

**Comment by mobitar** [comment]
Hmm good point, thanks.
