### ISSUE TITLE
Scrollbar not visible on black backgrounds

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#177]
[White background](https://www.dropbox.com/s/z55zep25n2sa35l/RPReplay_Final1566761006.mov?dl=0) 

[Black background](https://www.dropbox.com/s/7npa6fwezuewno7/RPReplay_Final1566761039.mov?dl=0) 

It seems like changing the scrollbar StyleKit variables has no effect.

**Comment by radko93** [comment]
Thank you for the report, this is fixed in the latest version. It will probably work if you have a dark theme enabled on your phone.
