### ISSUE TITLE
iOS: Left sidebar is complete white/without content

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/mobile#179]
The latest iOS version are not able to render content of the left sidebar, until you open a note and try again.

- start the app
- unlock via fingerprint
- list of notes are shown
- open left sidebar > blank / white
- close sidebar
- open a note
- go back to the list of notes
- open left sidebar > content is rendered

**Comment by mobitar** [comment]
I haven't been able to reproduce this. However, I've made some underlying updates to the framework that handles this, so hopefully that fixes this issue in the upcoming release.
