### ISSUE TITLE
Side bar not showing on iOS 13.0

### ISSUE THREAD

**Issue by sync-cpetty** [standardnotes/mobile#183]
iPhone X running iOS 13.0.

The hamburger sidebar does not load and am unable to select a note or tag. The last selected note does load when the app loads. Consistent with fresh launches even after device restart.

**Comment by mobitar** [comment]
I haven't been able to reproduce this. However, I've made some underlying updates to the framework that handles this, so hopefully that fixes this issue in the upcoming release.

**Comment by sync-cpetty** [comment]
I deleted the app and redownloaded and now cannot login. The same credentials work in the webapp and desktop app (Windows).

The username and password get me to the 2FA screen, but I get:

“Oops Invalid email or password.”

If I use an incorrect 2FA code it recognizes that with a different message. I’ve turned my VPN off but still cannot login.

**Comment by mobitar** [comment]
Please update to 3.0.11, which was recently released.
