### ISSUE TITLE
[Android][Security improvement] Disallow recents and screenshots

### ISSUE THREAD

**Issue by user8446** [standardnotes/mobile#184]
On Android, it would be a security improvement if screenshots were not allowed and the app was excluded from recent tasks like bank apps do.

At least for the recents from what I understand this would be an easy fix by adding this to the activity tag in the manifest:

`android:excludeFromRecents="true"`

and found this online for disallowing the screenshots: https://trinitytuts.com/prevent-application-content-from-screenshot-or-screen-recording-android/

I hope this helps

**Comment by mobitar** [comment]
This option is enabled if you have local passcode or fingerprint timing set to Immediate.
