### ISSUE TITLE
iOS unusable without sidebar and ability to login

### ISSUE THREAD

**Issue by christianpetty** [standardnotes/mobile#186]
![4979A941-DAB2-4149-935D-A3BC739D1209](https://user-images.githubusercontent.com/7821405/66091652-dfb20200-e545-11e9-9a5e-14e1981421e3.png)

iOS 13.1.2 on iPhone X

Before this happened I was not able to login with credentials that worked on both the web app and desktop. Restarts do not help.

**Comment by mobitar** [comment]
Update to 3.0.11.

**Comment by mobitar** [comment]
After some more testing and input from @bryvin, we were able to determine this has something to do with FaceID being enabled, and is still not fixed in 3.0.11. Will need to investigate further.

**Comment by christianpetty** [comment]
I updated and am able to login now. FaceID is on too. Thank you!
