### ISSUE TITLE
Universal Dark Mode

### ISSUE THREAD

**Issue by frvkl** [standardnotes/mobile#187]
As you might know, a standard has been developed to allow for seperate styles for both **light** and **dark** mode.

[https://webkit.org/blog/8840/dark-mode-support-in-webkit/](https://webkit.org/blog/8840/dark-mode-support-in-webkit/)
[https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

Are you planning into looking into this? 

If implemented, we can then adjust our preferences in the custom theme stylesheets.

This would be a great addition in the app & website.

**Comment by mobitar** [comment]
We'll be investigating this for iOS: https://github.com/standardnotes/mobile/issues/188

Not sure if we'd do anything for desktop/web. What's the state of dark mode on Android?

**Comment by frvkl** [comment]
Please see here, for the Dark Mode on Android:

[https://developer.android.com/guide/topics/ui/look-and-feel/darktheme](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme).

Looking forward to see the progress.

**Comment by fusionneur** [comment]
This app really needs a dark/black theme to get traction

**Comment by radko93** [comment]
Thank you for the report, this is fixed in the latest version.

**Comment by fusionneur** [comment]
awesome. thank you guys! you're the best :)
