### ISSUE TITLE
White text on white status bar background

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#195]
![4B71C0F9-8CAD-4AAA-8580-7E7799AF0BB6](https://user-images.githubusercontent.com/355541/67001007-db89f680-f0a6-11e9-9614-4551a9559911.jpeg)

iOS 13.1.3 (17A878)
iPhone XS

**Comment by bryvin** [comment]
This has been fixed in 3.0.18. If you still are experiencing this issue please let us know!
