### ISSUE TITLE
"Missing Keys" error constantly have to sign back in on pixel

### ISSUE THREAD

**Issue by kilo6eight** [standardnotes/mobile#206]
Using a Google Pixel 3a on latest Android 10 (GrapheneOS) running latest version of standard notes.

Constantly getting a "missing keys" error have to sign back in constantly. I think it might have something to do with setting a passcode on the app. When set, and you exit the app the missing keys error will occur. Not 100% tested this theory yet.

**Comment by VosaXalo** [comment]
Same issue here with Google Pixel 4 XL, Android 10 and standardnotes app updated.
I have disabled the fingerprint option because on Pixel 4 it's available only the face unlock. So I wanted to set a passcode, and I have found out this issue.

**Comment by mobitar** [comment]
Sorry about that. Caused by this: https://github.com/standardnotes/mobile/issues/204

Hoping to get a fix out soon.

**Comment by mobitar** [comment]
Issue is fixed with 3.0.17. However I'll be releasing through beta first on Google Play. You can download apk directly here: https://github.com/standardnotes/mobile/releases/tag/3.0.17
