### ISSUE TITLE
Android app crashes when opening large note

### ISSUE THREAD

**Issue by rdanielday** [standardnotes/mobile#21]
I saved a long article formatted in Markdown to the web app, but when I tried to open the same article in the Android app, the app has crashed multiple times. The article is about 4500 words, I'm not sure how many lines. While it's very long, I would think it wouldn't be too hard to open due to the very minimal formatting. Other notes open fine.

For reference, I'm an Extended user on desktop, so far just in the web application. I'm running Android 8.0 on a Nexus5x with the latest version of Standard Notes from the app store.

**Comment by mobitar** [comment]
Hmm that's strange. I just tested on a mediocre Android 7.0 device with a note with 10,000 words and it worked just fine. Perhaps it's something to do with Android 8. I'll look at the crash logs if there are any. Does this happen consistently, even when quitting the app completely and re-opening it?

**Comment by rdanielday** [comment]
So far it only seems to happen with this note. I have other longish notes, though this is by far the longest. It doesn't have any strange formatting or anything that should cause the app to crash. Here's a public link to the note through Standard Notes, for reference:

https://listed.standardnotes.org/d5P1Cha2qC

And here's the note content in a gist, so you can view the raw Markdown, as well:

https://gist.github.com/rdanielday/b2a00d221362c542bbcc120b6fd8aa1e

If there's any other data I can provide, let me know and I'll get it to you.

**Comment by rdanielday** [comment]
So I've uninstalled/reinstalled the app, and after crashing the first 4 or 5 times I tried to open the note, it now opens and is editable. So I'm still unsure exactly what was causing the problem, but it seems to be solved at this point.

Thanks for taking the time to look into this! I'll be sure to file an issue if anything new comes up.

**Comment by bryvin** [comment]
Closing as it is possible this may have been fixed without realizing it. If this issue still occurs please let us know!
