### ISSUE TITLE
Scroll behavior issue when switching view

### ISSUE THREAD

**Issue by Heziode** [standardnotes/mobile#216]
When I lauch the app, I arrived on not list, I can scroll normaly. If I open a note, and go back to note list, the behavior has changend, if I scroll, I need to keep the finger on the screen to do the scroll. 

Peraps it's a React Native issue, because I also have this issue with otfer app dedelopped with React Native.

My system: AOSiP 9 on Xiaomi Mi 8

**Comment by bryvin** [comment]
Is it possible you could record a video of this behavior? I have been unable to replicate this on my device or emulators.

**Comment by Heziode** [comment]
Link to the video: [[Android] Standard Notes - scroll-bug](https://diode.zone/videos/watch/4f350e0f-95ee-43e9-8763-8fc2a7994453)

**Comment by bryvin** [comment]
Perfect, thanks for the video! It looks like it's missing the momentum scrolling after returning to that view. What other app do you experience this issue with?

**Comment by Heziode** [comment]
The other app where I have also experienced this issue is [Le Cercle du Cashflow • Réseau social immobilier](https://play.google.com/store/apps/details?id=com.vasolutions.cashflowmastermind&hl=fr), and some others that I don't remember (becaused used, then deleted ^^)

**Comment by Heziode** [comment]
@bryvin,

Any progress on this issue ?

**Comment by radko93** [comment]
Hi, 
this should no longer be an issue. If you still encounter it please let me know.
