### ISSUE TITLE
Android app does not send protocol version when registering a user

### ISSUE THREAD

**Issue by chuckwagoncomputing** [standardnotes/mobile#22]
When I try registering a user using the Android app, it doesn't seem to send the protocol version.
Here are the params from the app:
`{"email"=>"test@test.com", "password"=>"[FILTERED]", "pw_cost"=>103000, "pw_salt"=>"iSl6viY7MNhipgRRH3oo6vMXDRvKHwc6IIVOZnlauYk=\n", "auth"=>{"email"=>"test@test.com", "password"=>"[FILTERED]", "pw_cost"=>103000, "pw_salt"=>"iSl6viY7MNhipgRRH3oo6vMXDRvKHwc6IIVOZnlauYk=\n"}}`

And here are the params from the webapp setting up a different account:
`{"password"=>"[FILTERED]", "email"=>"foo@test.com", "pw_salt"=>"de7359ee9a2929cfdd8176edc1ccd4e7207ccfaa0b4cc3d9432a974d660e37c2", "pw_cost"=>101000, "version"=>"002", "auth"=>{"password"=>"[FILTERED]", "email"=>"foo@test.com", "pw_salt"=>"de7359ee9a2929cfdd8176edc1ccd4e7207ccfaa0b4cc3d9432a974d660e37c2", "pw_cost"=>101000, "version"=>"002"}}`

I'm running my own server, and when I try to log into an account registered in the app using the webapp, I get the error:
`The protocol version associated with your account is outdated and no longer supported by this application. Please visit standardnotes.org/help/security-update for more information.`
However, I can not reproduce this using the official server.

**Comment by mobitar** [comment]
Fixed via 817ec34c7369f83a2c6333afcb8a1e707f8bc0c8
