### ISSUE TITLE
Exodus reports that the play store app has bugsnag tracking

### ISSUE THREAD

**Issue by user8446** [standardnotes/mobile#220]
If so, the user should have an option in the settings to be able to opt out of the bugsnag tracking/analytics for increased security/privacy.
However, the privacy policy states contradicting information:

> "Instead, we use an open-source, privacy-focused, and self-hosted Matomo analytics installation."

and

> "...contain no analytics or tracking software whatsoever."

**Comment by JulBor25** [comment]
I just discovered the same with NetGuard and Logs enabled. It's connecting to sessions.bugsnag.com, so we can probably just block it via hosts.

**Comment by mobitar** [comment]
We use Matomo only for our website, and not our apps. Our mobile app does indeed use Bugsnag for crash reporting. We do want to eventually introduce an option to opt out of that.

Here's the full quoted text for the record:

> To date, our applications, including web, desktop, and mobile, contain no analytics or tracking software whatsoever.

I guess you could argue that Bugsnag could fall under analytics, but this term is generally meant to imply custom behavior tracking, which we don't do.

**Comment by user8446** [comment]
Thanks a bunch for the explanation. An opt-out option would be a great especially since the theme of StandardNotes is privacy & security. Then the users can choose.

**Comment by gonewild22** [comment]
Is there any news about the implementation of an opt-out feature? I would really appreciate it! Thx a lot!

**Comment by mobitar** [comment]
@radko93 please explore this for v3.5 release.

**Comment by licaon-kter** [comment]
Bugsnag is open source indeed so that's not an issue.

But, if it's opt-out we'd need a `Tracking` antifeature in F-Droid. If it's opt-in we won't ;)

**Comment by chaserene** [comment]
please make this at least opt-outable, but preferably opt-in. it's scary for a privacy-conscious app that developers can look into anyone's app logs.

have you considered using local logs where nothing is sent by default, but if the user chooses to, they can send it to you?

**Comment by radko93** [comment]
@chaserene we are committed to creating a feature to opt out soon.

About using local logs, we don't have resources to build a a full fledged error/crash reporting solution like Bugsnag, so it's unlikely that we would replace it with something else for now. 

@licaon-kter I will have this in mind when working on this.

**Comment by radko93** [comment]
I wanted to share an update on this issue:
I implemented the opt out functionality and a beta is available now available to download from https://github.com/standardnotes/mobile/actions/runs/441154269. The same build will be released next week if everything works fine.

**Comment by licaon-kter** [comment]
Well, the app is unbuildable at the moment though, but nice addition.

**Comment by user8446** [comment]
Sign up for the beta through Google Play.
I just did and it updated to v3.5.14 with the error reporting option.

**Comment by radko93** [comment]
The update that contains it is out for everyone. We plan to make it opt-in next year.

**Comment by chaserene** [comment]
thank you @radko93! a nicety: after opting out, the app prompts me to restart the app to apply this change. the meaning of "restart" is vague here (close it such that it loses state? force stop? log out?). this could use some clarification.

**Comment by JaspalSuri** [comment]
Restarting the app should simply mean removing the app from the system's RAM/memory and then relaunching it, although I can see how a user might exit the app by returning to the home screen and simply relaunch the app.

**Comment by chaserene** [comment]
thanks Jaspal! so for all else who wonders: in Android, that's swiping the app "up" when you browse open apps.
