### ISSUE TITLE
Android beta build 3.0.20 crashes at startup

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/mobile#225]
Good day,

I just updated to the latest Android beta version 3.0.20 and it crashes at startup. I submitted the crash report through LineageOS so hopefully that should provide lots of information. If there is anything else I can do to help out, please let me know.

Thanks!

**Comment by mobitar** [comment]
Sorry about that! We just pushed up 3.0.21 which should fix this issue. It should be available within the hour.

**Comment by And96** [comment]
> Sorry about that! We just pushed up 3.0.21 which should fix this issue. It should be available within the hour.

Yes, now it's fixed. I can confirm.

**Comment by ddddavidmartin** [comment]
No worries at all, that's the joy of running beta builds. Works a charm again now, thanks for the quick fix!
