### ISSUE TITLE
3.0.21 (Testflight version): Note List's Scrollbar hanging in center of screen

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#226]
iPhone XS
iOS 13.3.1

**Comment by mobitar** [comment]
Screenshot? cc @bryvin

**Comment by christianhans** [comment]
![IMG_F316A2D1BFB8-1](https://user-images.githubusercontent.com/355541/73549952-ac0eb800-4411-11ea-8f54-eaefcbb1f096.jpeg)

**Comment by mobitar** [comment]
Lol, sorry for having you make a bunch of dummy notes. I suppose there could have been no other way. Does rotating the device and back fix the issue? Or an app restart?

**Comment by christianhans** [comment]
Haha yes. I should keep them for future screenshots!

Right now I don't know how to reproduce the bug. Restarting does seem to fix it. Once I figure out how to reproduce I will report back.

**Comment by bryvin** [comment]
I'll keep an eye out for this and so some research. I think this issue has been brought up before and fixed if I remember correctly. Thanks for reporting back if you have any reproduction steps! :)

**Comment by radko93** [comment]
@christianhans this should not happen in any recent version. Let me know if it's still an issue.
