### ISSUE TITLE
Android 10 new "back" gestures do not play well with menus

### ISSUE THREAD

**Issue by lriesebos** [standardnotes/mobile#228]
Android 10 has new "back button" gestures swiping from the left or right edge of the screen to the center of the screen. In the notes list of S. Notes there is a menu when swiping from the left edge and in the plain editor there is a menu when swiping from the right edge. It looks like the new back gesture of Android 10 does not play well with those menus. For example: when going "back" from the plain editor using a swipe gesture from the right edge the menu comes out a bit and the cursor moves position before the actual back gesture is detected.

Not sure what the best long-term solution could be, but in the worst case it could be convenient to have an option to disable the swiping of the menus. The user would have to use the hamburger buttons in that case.

**Comment by bryvin** [comment]
Hmm I was not aware of those new gestures, thank you for the heads up. I will discuss this with the team and see if we can come up with a good solution.

**Comment by radko93** [comment]
Thank you for the report. It's very hard for me to open the menus on Samsung device. If you feel this is still a problem with the latest version let me know.

**Comment by lriesebos** [comment]
On android 10 (android one with December update), using the "back gesture" from the plain editor still results in an event of going back to the list with notes followed by a gentle visual bump to the left and back of the list with notes. Funny enough, making the gesture from the right edge of the screen (gesture to the left) shows this visual behaviour but when swiping from the left edge of the screen (gesture to the right) no visual glitches appear. So in some sense, the double "back" behavior still exists visually when swiping from the right edge of the screen, but it does not result in practical issues.
