### ISSUE TITLE
VT alerts

### ISSUE THREAD

**Issue by IzzySoft** [standardnotes/mobile#23]
For a few versions now, [VT is throwing warnings](https://www.virustotal.com/de/file/87f39c3ba067e635b374fc3ba1ba6e4aabdd1feb5d6e94f4c53635e09bbbcbd2/analysis/1510684801/). It seems they are caused by `classes7.dex` and `classes3.dex` (shown when you click on "File details"). Is there anything that can be done about that?

**Comment by mobitar** [comment]
Unfortunately there isn't much I can do about false positives that throw off antivirus programs. The dex files are fundamental to the application. It's best to just add those to the whitelist.

**Comment by IzzySoft** [comment]
Was afraid of that – but I cannot whitelist things on VT. In the past, it seems that often some part of Android Studio was "responsible" – and after an update and recompile the warning was gone; other times it was a simple minor configuration change and recompile. So if there's anything pending … otherwise we'll simply have to wait and see when that happens then (one day there will be an update).

**Comment by mobitar** [comment]
Perhaps it has something to do with using a beta version of gradle? I'll try building with a production release and uploading the same to see if that works.

**Comment by IzzySoft** [comment]
Good idea. I've meanwhile left a comment on that report pointing here and saying it's probably a "false positive". That way folks checking it at least get a hint.
