### ISSUE TITLE
Android app crashes after switching from Secure Spreadsheet to Plain Editor

### ISSUE THREAD

**Issue by zazake0** [standardnotes/mobile#234]
Hi. After changing the editor of a note formatted by Secure Spreadsheet to Plain Editor, the Android app crashes whenever I try to open that note, regardless of whether I made the editor change on the Android app or the desktop app.
This does not happen when switching to another editor, nor does it happen on the Linux app.
It also does not happen when opening a regular note with Secure Spreadsheet without adding content to the spreadsheet (so that no spreadsheet formatting is added) and then switching back to Plain Editor.

**Comment by bryvin** [comment]
Thanks for the detailed report, how big are the spreadsheets that cause the crash, meaning is there a lot of cells with data in them?

**Comment by zazake0** [comment]
No, this happens as soon as one cell has data in it.


Le mar. 18 févr. 2020 à 17:31, Bryan Chauvin <notifications@github.com> a
écrit :

**Comment by bryvin** [comment]
Will need to investigate this, thank you for getting back to me!

**Comment by zazake0** [comment]
This is on Android 9 by the way.


Le mar. 18 févr. 2020 à 17:31, Bryan Chauvin <notifications@github.com> a
écrit :

**Comment by zazake0** [comment]
The issue has disappeared after upgrading to Android 10.

**Comment by JaspalSuri** [comment]
That's great to hear! Thank you for supporting us with Extended and for getting back to us to let us know that you are no longer experiencing this issue. Please don't hesitate to reach out to us in the future.

**Comment by zazake0** [comment]
Thanks for the great app!
