### ISSUE TITLE
Changing theme on iPad keeps previous theme for text area

### ISSUE THREAD

**Issue by dgraziotin** [standardnotes/mobile#239]
Steps to reproduce [iPad Pro 12.9"]:

- Open Standard Notes, default Blue theme is selected.
- Change theme to any downloaded theme (this one in the screenshot is Futura).
- Theme changes successfully, but the note text area stays with the old theme.

![IMG_0100](https://user-images.githubusercontent.com/153179/76071420-7b80e780-5f96-11ea-9a3e-0aeb423705f5.jpeg)

To fix:

- Kill the app and open again.

This is unrelated to the [need of downloading the theme again](https://github.com/standardnotes/forum/issues/892).

**Comment by JaspalSuri** [comment]
Hi, I’m sorry for the late reply.

How many times do you find yourself restarting the app? Would signing out and back in help? 

I’ll let the team know about this, of course. 

Thanks for bringing this and the other issue to our attention!

**Comment by mobitar** [comment]
Hmm, this is probably related to the fact that on tablets, the compose window is always open. Whereas on regular phones, you can only change themes by navigating to the side menu, then opening the compose screen, at which point, it will properly load up the correct theme.

We'd need to double check our code to make sure that we're actively listening to theme change events and reload live. Although, if the notes list does it, I don't see why compose wouldn't..

**Comment by dgraziotin** [comment]
> How many times do you find yourself restarting the app? 

Every time I want to change theme. 

> Would signing out and back in help?

Just tried this (logout, app killed, login, switch theme). It does not fix the issue.

> I’ll let the team know about this, of course.
> 
> Thanks for bringing this and the other issue to our attention!

No worries, I will report any issue I encounter. I want this to be the best notes app ever :-) and no worries, you actually replied to both issues less than 24 hours after I opened them. That is fast.

**Comment by radko93** [comment]
@dgraziotin can you check if reopening (opening another note and going back) the note fixes this in the latest version of the app?

**Comment by dgraziotin** [comment]
@radko93 apologies, I do not have Extended anymore, for testing this.

**Comment by JaspalSuri** [comment]
@dgraziotin Thanks for getting back to us. The latest version of the Standard Notes mobile app includes a free dark theme (and you can install [themes provided by the community](https://github.com/jonhadfield/awesome-standard-notes#themes) via the desktop or [web app](app.standardnotes.org) if necessary), so if you're still willing to test it out and let us know if the issue is fixed, we'd greatly appreciate it!

**Comment by dgraziotin** [comment]
@JaspalSuri that was easy then! I tested it and confirm it works. Will close the issue. I appreciate the fix!
