### ISSUE TITLE
Issue with search term persisting after app close

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#24]
User report:

I'm running Android 7.1.1 and Standard Notes 2.0.3.

Here's how to reproduce the bug:

(- You must have some notes in standard notes)
- Enter anything in the search box
- Press home button on your phone
- Go back to standard notes
- Search box doesn't show any input that there was before but the messages are still sorted by that search term. This can be very confusing.

**Comment by issmirnov** [comment]
Do you have any pointers to a potential root cause? I don't know React Native but would be willing to take a look. This bug bites me a few times a week :)

**Comment by mobitar** [comment]
This is still happening? Thought I fixed this. In any case, the search term is part of the OptionsState object, which is persisted to disk.

https://github.com/standardnotes/mobile/blob/master/src/OptionsState.js#L35:

```
 persist() {
    Storage.setItem("options", JSON.stringify(this));
  }
```

However, this object also has toJSON defined, which does not include the search term:

```
  toJSON() {
    return {sortBy: this.sortBy, archivedOnly: this.archivedOnly, selectedTags: this.selectedTags};
  }
```

So not sure why this issue is still happening.

**Comment by mobitar** [comment]
Fixed in v3.
