### ISSUE TITLE
Missing tags since 3.0.18

### ISSUE THREAD

**Issue by losuler** [standardnotes/mobile#241]
Seems there hasn't been any tags or releases since 3.0.18, which means the F-Droid build server isn't able to auto detect new releases.

**Comment by JaspalSuri** [comment]
Hi, sorry for the late response. Can you specify what you mean by tags? I'm sure whoever maintains the tag's listing on FDroid will know, but I want to inquire just in case. Any other relevant information would be helpful as well! 

I will report this info back to the team. I apologize for the lack of updates being pushed to F-Droid.

**Comment by losuler** [comment]
Sorry, I meant the tags on this git repo itself (https://github.com/standardnotes/mobile/tags) are what F-Droid uses to build new versions.

**Comment by mobitar** [comment]
On my queue to fix.

**Comment by mobitar** [comment]
Should be fixed now 👍https://github.com/standardnotes/mobile/releases/tag/3.0.21

**Comment by neekless** [comment]
The f-Droid version is still stuck on 3.0.17. Is the problem on f-droid's side?

**Comment by radko93** [comment]
Seems like it's a problem over there, 3.0.21 is in their config file (but I'm not that familiar with f-droid so this might not be crucial here) https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.standardnotes.yml

**Comment by radko93** [comment]
Seems like the last build fail to build on their side https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.standardnotes.yml#L175

**Comment by ningsongshen** [comment]
Compared to 3.0.17, these two lines are missing in 3.0.21. Would they cause any issues @radko93 ?

rm:
```
 - vendor/TrustKit/
```

scanignore:
```
- vendor/react-native-navigation/android/build.gradle
```

**Comment by ningsongshen** [comment]
Potentially relevant PR: https://github.com/standardnotes/mobile/pull/203/files

**Comment by losuler** [comment]
In case it wasn't already known, some information about build errors can be found at https://f-droid.org/wiki/page/com.standardnotes/lastbuild

**Comment by ningsongshen** [comment]
Based on the build error, we're missing the TrustKit submodule (not familiar with its purpose).

The submodule info was removed in this PR: https://github.com/standardnotes/mobile/pull/249, and the build started failing a few days after. :cry: 

@radko93 you mentioned that we needed to remove submodules but I didn't see if it was added back somewhere else. Could you check up on that? I'm not too familiar with react native...

**Comment by radko93** [comment]
@ningsongshen we don't use submodules anymore so that won't be an issue in the future.

**Comment by ningsongshen** [comment]
:ok: so I guess then the issue is that it is not building version 3.0.22, which is not good.

**Comment by uraza** [comment]
I discovered the app through F-Droid.
I can confirm that the version there is still stuck to 3.0.17. :/

**Comment by JaspalSuri** [comment]
Hi @uraza,

You can download the latest versions of Standard Notes' Android app [through GitHub](https://github.com/standardnotes/mobile/releases). 🙂 

Rest assured that we plan to update the app on F-Droid in the future! Currently the team is just swamped with development work, but we haven't forgotten about this. For what it's worth, the releases on F-Droid have been maintained by the community.

**Comment by JaspalSuri** [comment]
Hello everyone, @proletarius101 has graciously built the latest version of the APK and uploaded it to F-Droid! You should be able to download it from [here](https://f-droid.org/packages/com.standardnotes). 🙂
