### ISSUE TITLE
Android version APK

### ISSUE THREAD

**Issue by climatisation** [standardnotes/mobile#243]
Hello,
it's not really an issue, I'm sorry but
the direct download link to APK android is dead
https://standardnotes.org/extensions?downloaded=android
I tried to replace it with your latest release but the app isn't installing idk

**Comment by JaspalSuri** [comment]
Thanks for letting us know! I'm glad it's currently not an issue for you. It's on @mobitar's queue. (ref: #241)

**Comment by JaspalSuri** [comment]
I apologize for the late update. This was fixed by Mo, please let us know if you're still running into any issues!
