### ISSUE TITLE
UI for undo on Android

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#25]
On iOS there is the system-wide (and reluctantly used) shake-to-undo. On Android, doesn't look like there's such a feature.

**Comment by PunnyBoi** [comment]
Hi. Recently I feel the need for this feature twice (on android). I searched in Issue, and this was already opened. I think it is a much needed and a highly underrated feature. Are you planning to implement this feature on android soon?

**Comment by radko93** [comment]
Hi, we have a history feature in the 3.5 app where you can undo any changes.

**Comment by mortezadadgar** [comment]
> Hi, we have a history feature in the 3.5 app where you can undo any changes.

yeah but there's **no** button for undo and redo

**Comment by JaspalSuri** [comment]
I think we'll stick with the history feature for now and work towards improving that feature as needed before exploring implementing an undo and redo option.
