### ISSUE TITLE
Add "Make List"

### ISSUE THREAD

**Issue by primarto** [standardnotes/mobile#257]
Add a list so that items can be added, checked or unchecked items.
This would be very useful in addition to a simple note.

Something like this:

![14568ac9-0522-4b69-914d-1c7c2a8033a3](https://user-images.githubusercontent.com/62907157/82488982-2bb7b400-9ae1-11ea-89ba-d51957244da0.jpg)

_like "Notally from OmGodse"_

**Comment by cyb3rz3us** [comment]
Just curious, doesn't the **Simple Task Editor** give you this now?

**Comment by radko93** [comment]
@primarto I will close this issue for now, let us know if you need more help.
