### ISSUE TITLE
[mobile-dev] Possible peerDevDep conflict in dev-branch commit 96645df

### ISSUE THREAD

**Issue by cyb3rz3us** [standardnotes/mobile#258]
**GENERAL**

**App Version:** 3.0.21
**Platform:** mobile
**Branch:** dev

**ISSUE**

In the 96645df commit to the SN@2.31.0 mobile dev-branch, there is a possible conflict between **eslint** and several other devDependency packages.

The _package.json_ changed the **eslint** version from ^6.8.0 to ^7.0.0.  However, several other devDep packages still have peerDeps that specify ^6.0.0 as the highest version.

I provide more detail re: the conflicts below.

----

These 2 packages are explicitly specified in the devDependencies section:

```
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/eslint-plugin@2.34.0
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/parser@2.34.0
```
_**NOTE:** I realize that the version specified for both of these is **v2.31.0** and that **v2.34.0** is shown above.  However, both versions have the same peerDep of **eslint@^5.0.0 || ^6.0.0**_

```
npm info @typescript-eslint/eslint-plugin@2.31.0 peerDependencies
{ '@typescript-eslint/parser': '^2.0.0', eslint: '^5.0.0 || ^6.0.0' }

npm info @typescript-eslint/eslint-plugin@2.34.0 peerDependencies
{ '@typescript-eslint/parser': '^2.0.0', eslint: '^5.0.0 || ^6.0.0' }

npm info @typescript-eslint/parser@2.31.0 peerDependencies
{ eslint: '^5.0.0 || ^6.0.0' }

npm info @typescript-eslint/parser@2.34.0 peerDependencies
{ eslint: '^5.0.0 || ^6.0.0' }
```

----

These 2 are req'd by **@react-native-community/eslint-config@1.1.0** which is what is specified in the devDependencies section:

```
npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, required by eslint-plugin-react@7.19.0
npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, required by eslint-plugin-react-hooks@3.0.0
```

**DISCLAIMER:** I am relatively new to npm so I may have misunderstood what's going on here and if so, then my apologies.  If that is the case, then please let me know where I got this wrong.

Thanks.

**Comment by JaspalSuri** [comment]
Hi, thanks for bringing this to our attention!

@radko93 Please look into this whenever you get the chance. :)

**Comment by radko93** [comment]
@cyb3rz3us  thank you for checking on the dependencies. Please be aware of one thing: `dev` branch is currently in progress and is not deployed anywhere. Current code that is released is on `master` branch.

About eslint - this is only a dev dependency and we use just for testing the code so this does not affect production code at all. I will probably downgrade eslint as you have suggested anyway.

**Comment by cyb3rz3us** [comment]
@radko93 Thx for the information here.  I was going to modify the _package.json_ on my end and downgrade the eslint - sounds like that is an acceptible move.

Because this involved dev code and a devDep, should I forgo raising similar issues in the future?

**Comment by radko93** [comment]
@cyb3rz3us definitely an acceptable move. You can submit issues related to `dev`, but keep in mind code here might not be fully working.

**Comment by cyb3rz3us** [comment]
Very good  --- thanks again @radko93.
