### ISSUE TITLE
Text cuts off when adding newlines

### ISSUE THREAD

**Issue by zanedb** [standardnotes/mobile#26]
I have created a demo note, with [some sample lorem ipsum text](http://websitetips.com/articles/copy/lorem/) (I also combined it all into one paragraph).

In that demo note, when I create a newline at the bottom, it cuts off the top. This is as far as I can scroll up with a newline:
![screenshot1](https://user-images.githubusercontent.com/16865690/33142736-55cd89ce-cf6c-11e7-9ea4-c0284a24a6cc.jpg)

Then, when making 5 newlines like so:
![screenshot2](https://user-images.githubusercontent.com/16865690/33142757-674412c2-cf6c-11e7-97a7-310277fae402.jpg)
It cuts off much more:
![screenshot3](https://user-images.githubusercontent.com/16865690/33142767-737900c0-cf6c-11e7-81ef-c150c4b87a6e.jpg)
(see the first screenshot for how many lines it cut off).

This may be a padding issue. Also, I've noticed it happening other times too but was unable to replicate it. If it happens again I'll take a screenshot.

Tested on latest Android version, not yet tested on iOS.

**Comment by mobitar** [comment]
Looking into this now. What you describe here is definitely just a padding issue which I could not find an easy way around. Checking now to see whether this affects actual scrolling behavior as reported in #80.

**Comment by mobitar** [comment]
We'll track this issue here: https://github.com/standardnotes/mobile/issues/130
