### ISSUE TITLE
Cannot build the project. No such file or directory: 'init'

### ISSUE THREAD

**Issue by Hamalet** [standardnotes/mobile#263]
I downloaded the project and ran 'yarn init' in terminal, but got error "No such file or directory: 'init'".

**Comment by radko93** [comment]
Hi, the codebase is under heave development now. If you want to build the app that is in production now, switch branch to master and follow README on that branch https://github.com/standardnotes/mobile/blob/master/README.md. If you want to build dev branch you need to check out on that branch.

**Comment by Hamalet** [comment]
> Hi, the codebase is under heave development now. If you want to build the app that is in production now, switch branch to master and follow README on that branch https://github.com/standardnotes/mobile/blob/master/README.md. If you want to build dev branch you need to check out on that branch.

Ok, thanks.
