### ISSUE TITLE
Bottom navigation bar not stylized on Android

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#264]
![8WVM599N6_5cZmGDbEUOoFsq0BLrN1VDjWdf8BvcntA](https://user-images.githubusercontent.com/3277844/85554467-8bc2de00-b5ea-11ea-9c97-efa7bf3fc1f8.jpg)

[Source](https://www.reddit.com/r/StandardNotes/comments/he45rp/android_issue_dark_themes_have_a_jarring_white/)

**Comment by radko93** [comment]
Duplicate of https://github.com/standardnotes/mobile/issues/256
