### ISSUE TITLE
Light splash screen with dark theme

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#265]
I'm using Standard Notes 3.0.22 on a Redmi Note 7 Pro running Android 10.  
With both, the system theme set to dark and Midnight set as the current theme and the current dark theme, the app's splash screen is still a bright white.  
Can the app take into account at least the system theme setting and offer a dark splash screen?

**Comment by JaspalSuri** [comment]
Thanks for creating this issue on GitHub! I'll keep note of it so it'll be reviewed after/during the rewrite. :)

**Comment by radko93** [comment]
@lokesh-krishna the app will now use a dark splash screen by default.
