### ISSUE TITLE
[Bug] The authentication screen doesn't appear in the app switcher after exiting the app (iOS 13.5 | iPhone 6s/+)

### ISSUE THREAD

**Issue by bastiel** [standardnotes/mobile#266]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.**
Yes

When you open the app switcher (double tapping the home button), the authentication screen will appear and hide the contents of the app (notes, titles, settings, etc). However, if you simply exit the app by tapping the home button once then double tapping for the app switcher, the authentication screen will not appear, and whoever has the phone will be able to read the contents of the app (again, not everything, but enough for them to know that you’re writing about something). This makes it less secure and private. 

**Describe the solution you'd like
A clear and concise description of what you want to happen.**

I would like the same existing feature implemented for this scenario: the authentication screen goes up in the app switcher preview after exiting the app thus preventing contents of the app to be shown. 

**Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.**

One alternative would be blurring the app switcher preview after exiting the app. 

**Additional context
Add any other context or screenshots about the feature request here.**

Picture 1 (below) shows the app switcher after double tapping the home button inside the app: 
![8F7338A3-7189-4FEC-A922-EBD0226E9792](https://user-images.githubusercontent.com/33913840/85892690-9e861000-b7ae-11ea-896e-1eb39a88d4f2.jpeg)

Picture 2 (below) shows the app switcher after exiting the app via single tapping the home button (NOT ending it via swipe) and then double tapping the home button anywhere on the phone:
![86DB36AD-D546-4730-8A2C-38B02194AFFB](https://user-images.githubusercontent.com/33913840/85892813-d8571680-b7ae-11ea-9ef6-4f27e1c0b57f.jpeg)

Picture 3 shows an example of this feature; Bitwarden shows its brand when you exit the app and activate the app switcher via double tapping the home button (funny enough, it doesn’t show up when double tapping the home button inside the app like Standard Notes):
![374237C7-F544-4CE0-A133-C97056308B58](https://user-images.githubusercontent.com/33913840/85892987-34219f80-b7af-11ea-9f66-f7da8f00cb9b.jpeg)

**Comment by mobitar** [comment]
I've transferred this issue to our mobile repo so that our mobile developer can take a look when he gets the chance.

**Comment by radko93** [comment]
Thank you for the report, this should fixed in the latest version.
