### ISSUE TITLE
Out of two conflicted copies, only one is tagged as "Conflicted copy"

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/mobile#270]
Related:
* [desktop/issues/576](https://github.com/standardnotes/desktop/issues/576)
* [desktop/issues/577](https://github.com/standardnotes/desktop/issues/577)
* [mobile/issues/271](https://github.com/standardnotes/mobile/issues/271)

What the title says. I have three copies of the same note (so two conflicts), but only one has the red tag. As far as I can tell, this all happened while I made no changes to that note.

**Update**: since sending this issue, all copies lost their "Conflicted copy" tag. It's as if SN began treating the conflicts as legit standalone notes and maybe even started syncing them (because now I also have three copies on desktop, the same as on mobile, as opposed to the two I had previously).

Version: Standard Notes Android 3.0.22

![android](https://user-images.githubusercontent.com/7106231/87245575-a00a3600-c446-11ea-9f91-12dddef4c021.png)

**Comment by leafcutterant** [comment]
Issue updated to indicate that now all red tags are lost.

**Comment by JaspalSuri** [comment]
Hi, I'm sorry about all of the issues resulting from this and am incredibly grateful for all of the reports! I'll package them together for the devs to review. Hopefully the refactor will crush bugs like these for us (but if not, we'll definitely take a look into it). :)

**Comment by radko93** [comment]
This might have been changed already in the latest version after the rewrite, if you still have issues please mention me.

**Comment by chaserene** [comment]
@radko93 yes, this is still present.
