### ISSUE TITLE
Conflicted copy didn't inherit tag on mobile

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/mobile#271]
Related:
* [desktop/issues/576](https://github.com/standardnotes/desktop/issues/576)
* [desktop/issues/577](https://github.com/standardnotes/desktop/issues/577)
* [mobile/issues/270](https://github.com/standardnotes/mobile/issues/270)

I ended up with three copies on desktop and three copies on mobile of the same note. This note has only one tag, a very simple one, used for displaying it with the Folders extension on desktop. Since neither client applied the "Conflicted copy" tag properly (see related issues), it's hard to tell in which order the copies came to be (especially since it also seems that some conflicts were synced across devices). But what I know is that on mobile, one of the three copies no longer has the tag, indicating inheritance issues.

Version: Standard Notes Android 3.0.22

**Comment by radko93** [comment]
Hi, we released a big refactor in November that should fix issues like that. Please let me know If the issue occurs again.
