### ISSUE TITLE
Biometrics Prompt Bug

### ISSUE THREAD

**Issue by msoose** [standardnotes/mobile#274]
While on the authentication page, hitting the multitasking button keeps the biometrics dialog up. See below, window has been taken out of focus yet the dialog is still visible.

Running Android 10 (LineageOS 17.1) with Standard Notes 3.0.22 installed from the Play Store.

![1](https://user-images.githubusercontent.com/30473690/88468156-a95ebe00-ce9c-11ea-9fa8-03bb513d2fa1.png)

**Comment by radko93** [comment]
@msoose thanks for your report! We are working on a new version of the app and I will try to get this resolved.

**Comment by msoose** [comment]
Interestingly, this is no longer happening on the same 3.0.22 version with the latest build of LineageOS 17.1 / Android 10 on my device. 

Unsure if this change came from AOSP or a Google  Play Services or some framework update.
