### ISSUE TITLE
Mobile login - need to trim user email input whitespaces..

### ISSUE THREAD

**Issue by Nik-olo** [standardnotes/mobile#278]
This happened when I tried to login. I did not understand why I was getting an error. I am using a password manager to enter the email and password and there was a whitespace in the end of the email address.

iOS app (v3.0.23)

solution: The whitespace could be trimmed on signin on app? 

![Image of bug](https://i.imgur.com/EOaStnD.png)

**Comment by JaspalSuri** [comment]
Hi @Nik-olo,

Thank you for highlighting this issue! I apologize for the inconveniences caused by the trailing white space. I'll pass this along to the team for further review. 🙂

**Comment by radko93** [comment]
Thank you for the report, this should be fixed in the latest version.
