### ISSUE TITLE
Bug: 3.5.0 does not seem to respect text size setting on iOS

### ISSUE THREAD

**Issue by SiGamma** [standardnotes/mobile#298]
Hi, 3.5.0 update seems to ignore text size settings, in plain and all other editors. Not sure that it affects the note list, but note body text really struck me as huge when I opened a note (I use the smallest font size). iPhone 11, iOS 14.1.

**Comment by radko93** [comment]
Thanks for your report @SiGamma, we will be releasing a new version soon that should resolve this issue.
