### ISSUE TITLE
App is asking to delete local data after upgrade to 3.5

### ISSUE THREAD

**Issue by mihail-sky** [standardnotes/mobile#300]
I've upgraded the app to version 3.5.0 today. On launching the app I can see a message saying I have a previous installation with suggestions to "Delete Local Data" or to "Quit App". If I quit and launch the app again, I get the same message. This is on iOS 14.1.

**Comment by radko93** [comment]
@mihail-sky sorry for your inconvenience. Did you use your app recently? Did you restore an iCloud backup?
If you have an account you can sign in on the website https://app.standardnotes.org/, check if all of your notes are there. If yes, you can safely Delete local data and then sign in again.

**Comment by redcella** [comment]
Im having the same issue.  I also do not have an account.  I really hope my notes aren't gone.

**Comment by mihail-sky** [comment]
@radko93 I also do not have an account. I use the app daily. I don't have a back up, solely using it on my phone.

**Comment by radko93** [comment]
@mihail-sky @redcella what are your device models?

**Comment by redcella** [comment]
@radko93 
iPhone 8 plus
iOS 14.1
Standard Notes 3.5.2 using TouchID to unlock notes.

**Comment by mobitar** [comment]
We've identified the source of this issue and will be rolling out a fix asap. Please do not uninstall the app or do anything else, otherwise you risk deleting your data. We'll update this thread once the release is out.

Just for your own peace of mind, you should take a device wide snapshot as soon as you can. (iCloud backup of your device, for example).

**Comment by radko93** [comment]
The update is now live on iOS, can you check if you can access your notes? We strongly recommend to have a backup or create a free account to sync your data in the future.

**Comment by redcella** [comment]
@radko93 

I now have access to my notes!  Thanks a lot for the quick fix.  Much appreciated.

Side note: there is a lot of flickering (shifting of the notes down and then back up again) in the notes list now.  I believe it has to do with the “Data not backup up” notification popping up and disappearing 4 or 5 times a second.

**Comment by radko93** [comment]
Thanks for the report, I will check that.

**Comment by mihail-sky** [comment]
I've upgraded to 3.5.3 and I have access to my notes again, thanks for the help!

**Comment by JaspalSuri** [comment]
We're so happy to hear that; thanks for letting us know!
