### ISSUE TITLE
Swiping right to dismiss a notes options menu is insensitive

### ISSUE THREAD

**Issue by PartialVolume** [standardnotes/mobile#302]
Standard Notes V3.5.1 (3000240) on HTC Pro 20. Android V10. Build no 1.01.2401.1

I've found that when you open a notes option menu (the menu where you create tags, protect and lock etc) it's difficult to dismiss the options menu by swiping right except by starting the swipe from the extreme left edge of the screen. With other menus in standard notes they are far more responsive and allow a swipe to start mostly anywhere on the screen. The options menu does dismiss correctly by clicking on the three bar button.

From a user's perspective the program therefore feels unresponsive when trying to dismiss the options menu with a right swipe as the swipe must start at the extreme left edge of the screen.

**Comment by radko93** [comment]
@PartialVolume thanks for your report. Swipe gesture is currently disabled for notes menu but we will try to turn it on again soon.

**Comment by PartialVolume** [comment]
Ok thanks 👍

**Comment by radko93** [comment]
Thank you for the report, this is fixed in the latest version.
