### ISSUE TITLE
iOS Upgrade to 3.5 prevents access to notes

### ISSUE THREAD

**Issue by snowbound** [standardnotes/mobile#303]
Upgraded Standard notes to 3.5 on iOS 12 here and no longer able to access notes. Get a message to upgrade of your local storage structure and that I have to enter my key. I do so and am told to reenter key. Windows10 3.5.4 has no problems with the password.

This is happening on 2 iOS 12 systems.

**Comment by radko93** [comment]
Hi, did you reenter your passcode after? Was the passcode accepted?

**Comment by snowbound** [comment]
I have entered multiple times and it does not work yet the Windows version has no such issue with the same passcode.

**Comment by radko93** [comment]
What is your exact iOS version + device name?

**Comment by snowbound** [comment]
Ios 12.4.8 ipadmini2

**Comment by snowbound** [comment]
I see "invalid value Please try again" after entering the passcod

**Comment by snowbound** [comment]
Still seeing the prompt on iOS 12 devices to "enter your application passcode" and I enter the decryption passcode that works fine on Windows10 install of Standard Note.  Yet on iOS 12 I get "valid value Please Try again" This is after upgrading one iOS 12 device to 3.5.2

**Comment by radko93** [comment]
@snowbound I'm really sorry this is happening for you. We are investigating this issue, but in the meantime, if you can confirm you have access to your notes on a different device (like Windows) you can reinstall the app and try to sign in again. You can also verify if your account works properly by signing in on https://app.standardnotes.org/

**Comment by snowbound** [comment]
Yes windows app works fine and so does website it is only iOS having the issue. I notice that on either ioS 12 device when the app runs the screen briefly blanks out. Then comes back prompting me for the application passcode.

**Comment by radko93** [comment]
Did reinstalling the app helper with this issue or it still occurs?

**Comment by snowbound** [comment]
Ok, I deleted the app off one of the iOS devices and reinstalled it and logged in and it is working. 

I am wondering if the issue I was seeing was because both of these iOS devices uses a passcode lock which is what I was entering. I did try entering the password for my account prior to reinstallation but that did not make a difference.

**Comment by JaspalSuri** [comment]
There appears to be an issue related to the passcode lock, so you might be right. In any case, we're definitely looking it!

**Comment by radko93** [comment]
I will close the issue, if you have any other issue please contact us.
