### ISSUE TITLE
can't sign in after upgrade to protocol v004 and re-installation of app

### ISSUE THREAD

**Issue by chaserene** [standardnotes/mobile#305]
Android version 3.5.2, website APK

I managed to solve #304 by forcing my account to upgrade to v004 by changing my password in the desktop client. however, at this point some of my notes that were recently edited on desktop didn't show up on mobile. the app also displayed an orange "potentially out of sync" line in the labels sidebar which I've never seen before.

I logged out to try to regain a full sync of my notes. the app said something about detecting and older installation, which I don't understand at all, but it wanted me to delete all local data. I pressed yes. to make sure no old stuff will interfere with the app, I went on to delete the app cache from Android, then the whole application storage, and then uninstall the app itself.

I reinstalled it but now I can't log in on mobile at all! I'm 100% positive my mail address and password are entered correctly (they work on desktop), but I keep getting "Oops. Invalid email or password." what is going on?

**Comment by radko93** [comment]
As a debug step, can you check if you can sign in with the same credentials on the web app?

**Comment by chaserene** [comment]
I don't trust my notes with JS downloaded from a website, so I won't be able to do that for you.

by the way, mystery solved, see the explanation in #307. closing this.
