### ISSUE TITLE
keep website link to APK updated to the latest release

### ISSUE THREAD

**Issue by chaserene** [standardnotes/mobile#307]
so it turns out #305 and a whole crop of my other problems was due to the fact that the [Android section of the official website](https://standardnotes.org/extensions?downloaded=android) still links to the 3.0.22 version. I was using that while I was convinced I'm using the latest (3.5.2).

please don't forget to update this link in the future when you do a new release. it's an important one.

**Comment by JaspalSuri** [comment]
Hi @chaserene,

The website should point to the latest version now (v3.5.3). Thank you for letting us know!

**Comment by landry314** [comment]
Issue #292 could also cause this problem of people thinking they have the latest version. I'm glad I came to the github page!

**Comment by JaspalSuri** [comment]
Hi @landry314,

That's a good point! I went ahead and reached out to the [F-Droid](https://f-droid.org/) team to see if they could include a link to one of our official [releases page for the mobile app](https://github.com/standardnotes/mobile/releases) on [Standard Notes' listing on F-Droid](https://f-droid.org/en/packages/com.standardnotes/).
