### ISSUE TITLE
Minimal MarkDown Editor doesn't appear in 3.5.3

### ISSUE THREAD

**Issue by chaserene** [standardnotes/mobile#313]
Android 9
3.5.3, downloaded from GitHub

IIRC it was still there in 3.5.2. but this may be connected to #312.

**Comment by JaspalSuri** [comment]
Hi @chaserene,

It's possible that the two are related. Can you try [version 3.5.5](https://github.com/standardnotes/mobile/releases) and let me know if that helps? It doesn't specifically aim to fix the "phantom account issue", but I am currently able to access the Minimal Markdown Editor.

**Comment by chaserene** [comment]
glad to report that the editor is available again since 3.5.5. closing this.
