### ISSUE TITLE
Automatic theme switching does not work anymore

### ISSUE THREAD

**Issue by wsid3** [standardnotes/mobile#314]
I have set the corresponding themes in the menu to 'current light theme' and 'current dark theme', but it doesn't switch automatically when I switch the system theme of my mobile. It happens since the 3.5.x update, previous versions worked as expected.

Version: 3.5.3
Android 10

**Comment by radko93** [comment]
Thanks for your report. Indeed the theme does not update automatically, it only updates when you restart the app. I will try to address sometime soon.

**Comment by radko93** [comment]
Hey, this should be fixed in the latest version. Please check.

**Comment by wsid3** [comment]
Works now, thank you.
