### ISSUE TITLE
Markdown Pro/Math

### ISSUE THREAD

**Issue by Cryptomamy** [standardnotes/mobile#319]
Hi Guys,

I love the extensions Markdown Pro and Markdown Math !

I would like to know if you are going to create an Extension with Pro and Math combined

That would be really cool as I put some codes with mathematical symbols in the explications of my code and would make it a lot easier on the visuals.

Thanks a lot !

**Comment by JaspalSuri** [comment]
Hi @Cryptomamy,

>I love the extensions Markdown Pro and Markdown Math!

We're glad to hear that!

>I would like to know if you are going to create an Extension with Pro and Math combined

Thanks for the suggestion! We currently don't have plans for this (and it might not be technically possible yet), or adding KaTeX or LaTeX support in the Markdown Pro Editor, but you can create threads suggesting support for it in the [Easy Markdown Editor's](https://github.com/Ionaru/easy-markdown-editor) and [Upmath repos](https://github.com/parpalak/upmath.me), which is what Markdown Pro and Markdown Math are based on, respectively. From there we can carefully pull in the changes made to the editors.

I'll forward your request to the team, though!

**Comment by Cryptomamy** [comment]
@JaspalSuri Thanks for your answer !

> KaTeX or LaTeX support in the Markdown Pro Editor, but you can create threads suggesting support for it in the Easy Markdown Editor's and Upmath repos, which is what Markdown Pro and Markdown Math are based on, respectively

I will do that, thank you for suggesting it.
