### ISSUE TITLE
decrypted export notes are not in readable form

### ISSUE THREAD

**Issue by sidmint** [standardnotes/mobile#320]
When I export in decrypted way and view the file by plain text editor, i cant see the notes in readable text and things still seem to be encrypted. I expected to see notes in readable text instead since it's decrypted.

**Comment by JaspalSuri** [comment]
Hi @sidmint,

This is a known issue and we plan to provide a fix for this soon. 

Thank you for reaching out to us! I've deleted your device's details. 🙂

**Comment by sidmint** [comment]
yeah, app updated and issue is resolved, thank you.

**Comment by JaspalSuri** [comment]
Thanks for letting us know! You're most welcome (on behalf of our mobile dev). :)
