### ISSUE TITLE
[Help Wanted] Invalid Application Passcode

### ISSUE THREAD

**Issue by SanshokuPan** [standardnotes/mobile#322]
I don’t understand why this happened, but I updated my iPhone 8 Plus and when I went to type in my passcode and use my biometrics, the menu disappeared and this prompt popped up:
![E2BCBA25-A510-491A-BADC-F6322DAFA610](https://user-images.githubusercontent.com/74573264/99321222-f4795400-2832-11eb-8a7f-ba842b8d2db1.jpeg)

I put in my usual passcode and it says it’s invalid. Even put in my password and an older passcode and no luck. I can’t access anything.

**Comment by SanshokuPan** [comment]
Okay, I put in the passcode. This is what happens:
![2DA3F058-779A-4DF9-9923-3E410515EB12](https://user-images.githubusercontent.com/74573264/99430181-9ef28500-28ce-11eb-8c7c-e29eed83bd4f.jpeg)

**Comment by JaspalSuri** [comment]
Thank you for letting me know. It's something that the team is trying to find a fix for.

Do you have an account with us by any chance? Can you log into the [web app](http://app.standardnotes.org/), and if that doesn't work, can you log into the [legacy web app](http://app-legacy.standardnotes.org/)?

**Comment by radko93** [comment]
@SanshokuPan do ever had this popup before (before updating your iPhone)?

**Comment by SanshokuPan** [comment]
I was able to access my notes through the web app. As for the pop up. It’s the first time I’ve seen it since downloading the app. It never came up with the many updates over the years. Only happened with the new update.

**Comment by JaspalSuri** [comment]
>I was able to access my notes through the web app.

Thanks for letting us know! In this case, I would suggest exporting an encrypted and decrypted backup via the web app through the **Account** menu, whose button is located in the bottom left corner of the web & desktop apps. From there, reinstall the app on your phone and log in again. It shouldn't ask for the passcode again.

**Comment by SanshokuPan** [comment]
Okay, I backed up everything and deleted the app on both my iPhone 8 Plus and my iPhone 12 Pro Max and I was able to access my notes through the iPhone 12. Thank you!

**Comment by JaspalSuri** [comment]
Thank you so much for doing so and for letting us know!
