### ISSUE TITLE
after login, don't display "No notes." while notes are loading

### ISSUE THREAD

**Issue by chaserene** [standardnotes/mobile#328]
after you log in (with mail address and password), it can take quite a long time until your notes appear. until then, you see this screen:

![image](https://user-images.githubusercontent.com/64873595/100395083-ce785e80-303f-11eb-86df-1cae6d339d29.png)

which makes me freak out every time I log in (I need to do that quite frequently recently) because I think all my notes were lost. could you replace it with something like "Loading notes..."?

**Comment by JaspalSuri** [comment]
Hi @chaserene,

Thanks for pointing this out. I agree that it can be improved and I'll pass it along to our mobile dev for review. I can see how a user might sign in and think that there's something wrong, and then sign out and sign back in again to see if their notes will load. In the worst case scenario, if they forgot or lost access to their password, then they wouldn't be able to sign in again.

**Comment by radko93** [comment]
Please check the new update @chaserene with a fix for that. Thank you for reporting that.
