### ISSUE TITLE
Extensions should not require a backend server to be up if you used them before / have installed them

### ISSUE THREAD

**Issue by theontho** [standardnotes/mobile#330]
**Describe the bug**
When I went to edit a note on my phone today, I got a 5XX error page instead of my note.  It actually surprised me.  I had to switch to the plain text editor from a markdown editor to edit my note again.  I'm guessing the big AWS outage caused this.

**Expected behavior**
Even if an extension server is down, it should work locally to edit your notes with it.  Some sort of caching mechanism?  Also makes it worrying from a security perspective since random javascript can be run on the note if the extension source server is compromised?  Maybe look into baking in these extensions as part of general updates since most of them come from the SN company anyway?  Less stuff you have to audit as a result.

At the very least show a more friendly error message and a recommendation to change your editor so you can fall back to the plain text editor for now.  Maybe put a button to do so in the error page also.

**Comment by JaspalSuri** [comment]
Hi @theontho,

According to Mo, [here](https://www.reddit.com/r/StandardNotes/comments/g3cg33/so_much_upside_but_whats_up_with_the_nonexistent/fnzkeid/):
>We have offline editors on desktop. For mobile, it's on our radar. We haven't had as much capacity as we'd like to do work on the mobile app, but this is changing, as we've brought on a full time mobile developer :) There are a few things ahead of offline editors in the queue for mobile, but definitely something we plan on getting to.

>I'm guessing the big AWS outage caused this.

This is correct. I'm sorry for the inconveniences that were caused by this.

> At the very least show a more friendly error message and a recommendation to change your editor so you can fall back to the plain text editor for now. Maybe put a button to do so in the error page also.

Thanks for the feedback here, I'll be sure to pass this along to our mobile dev to consider whether we can utilize this until the editors are accessible offline on the mobile apps.

**Comment by JaspalSuri** [comment]
>At the very least show a more friendly error message and a recommendation to change your editor so you can fall back to the plain text editor for now. Maybe put a button to do so in the error page also.

The app automatically switches to the Plain Editor in my experience. What version of the app are you currently using? Are you still able to reproduce this issue?
