### ISSUE TITLE
Sync problems

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/mobile#333]
The Android app (3.5.10 3000254) stops syncing randomly and without warning on Android 9 (observed on two devices, Huawei Honor 9 and Lenovo Tab P10). The app appears to sync, but nothing is transferred to Standard Notes desktop or web. Restarting (and resyncing) the app doesn't help. Only a sign out- and in solves the problem. The sync error appears more frequently on my phone, Huawei Honor 9, that switches between networks often (wi-fi and/or 4G).

**Comment by JaspalSuri** [comment]
Hi @onlinemumie,

I'm sorry to hear that. Can you apply the changes that weren't synced to either the desktop or web app, then sign out of the devices using the Android app, clear the apps' storage and cache, and then sign into them again? That should resolve the issue. 

To clear each app's storage and cache, locate it in the app drawer, press and hold it until the **App Info** option appears, and then locate and select the options to delete the app's storage and data. 

Please let us know if you have any other questions.

**Comment by mobitar** [comment]
@onlinemumie when this issue happens, does your account email disappear from the Settings menu? i.e does it say something like "Sign out (undefined)"?

**Comment by onlinemumie** [comment]
Yes it does! I have it now: "Sign out (undefined)". The Android app seems to be working, but nothing is synced to the server.

**Comment by mobitar** [comment]
Hmm, this is then an issue we're aware of but cannot replicate. Any additional info you can share regarding timing of this happening could be helpful. Some possible questions:

1. How long after signing into your account on mobile do you see this behavior?
2. Do you have passcode/biometrics configured?
3. Any other observations?

**Comment by onlinemumie** [comment]
OK, let's see ...
1. Sometimes after a few hours, sometimes after a day or so.
2. Yes, biometrics is configured.
3. It happens more often on my phone that switches between Wi-Fi networks and 4G. It rarely happens on my tablet that stays on the same Wi-Fi. Also, biometrics is configured on both devices.

**Comment by mobitar** [comment]
What we're going to do is for now at least put an alert in place that alerts you when your app has entered into this invalid state. This way you're not guessing at it. Hopefully at @radko93 will get this out sometime today or tomorrow.

**Comment by wsid3** [comment]
For me, the sync problems and the 'sign out (undefined)' in the settings menu starts to appear  when I close SN with the 'close app' function of the 'One Hand Operation +' (https://play.google.com/store/apps/details?id=com.samsung.android.sidegesturepad) official Samsung application.
It only happens when I have biometrics enabled.
It's always reproducible.
Galaxy S10 Android 10

**Comment by radko93** [comment]
@wsid3 I can reproduce that, thank you!

**Comment by radko93** [comment]
We released a new update that should fix this issue, please try it and let me know!

Thanks to @wsid3 for the reproduction steps that helped in nailing down the issue!

**Comment by wsid3** [comment]
It works in my case, thank you.

**Comment by onlinemumie** [comment]
It's been working fine ever since the update. Very good.
