### ISSUE TITLE
[iOS] Very small font size after 3.5.14

### ISSUE THREAD

**Issue by vladolaru** [standardnotes/mobile#337]
After the latest update (3.5.14), using the plain text editor, the content font size is very small. I have tried changing the font size from the system settings but only the note title adjusts, not the note content.

I am using the latest version of iOS (14.3).

**Comment by alexbates** [comment]
Same problem. This issue is new to version 3.5.14. Replicated on iOS 14.3 and 14.2, two different iPhone models.

**Comment by joyalicegu** [comment]
Fixed by https://github.com/standardnotes/mobile/commit/178d999ee1a43adefeaad2676b6d51fdabca6a87

**Comment by vladolaru** [comment]
Well that was fast. Good job. Keep it up 👏
