### ISSUE TITLE
Security Flaw in Privilege Management of Protected Notes

### ISSUE THREAD

**Issue by landry314** [standardnotes/mobile#340]
In the "Manage Privileges" section in settings if you have "Application Passcode" set for "View Protected Notes" but "Application Passcode" NOT selected for "Manage Privileges" then someone trying to view protected notes can simply enter settings and change the setting for "View Protected Notes" then go back and view the notes.

There should not be a way to have the feature to passcode protect protected notes on while also having the feature to deselect this feature also be available! This is a security flaw. This is especially troublesome when you realize that these are all off by default meaning a user could find himself in the Manage Privileges section and see he can turn on a way to passcode protect his protected notes but not realize he also has to passcode protect the ability to change this too! He could easily miss this and think he is protected but he is actually not!

**Comment by JaspalSuri** [comment]
Hello @landry314,

Thanks for bringing this to our attention! This issue will actually be addressed in our next update to how privileges are handled by the apps. 😃  

We've also taken note of the issue where protected notes are accessible on the mobile app, if it's already unlocked, and will address that as a part of the update.

**Comment by JaspalSuri** [comment]
Hi @landry314, I'm going to close this thread since this issue was addressed in v3.6 of the desktop and [web](http://app.standardnotes.org/) apps. When turning off your passcode, the app will always ask for your passcode across all of our apps.
