### ISSUE TITLE
Occasionally the last few letters of an edit are lost

### ISSUE THREAD

**Issue by wlevine** [standardnotes/mobile#342]
This has happened to me several times recently, but unfortunately I have not been able to find a way to reproduce it 100%.

What happens:
* Type something in a note on the Android app. For example: "Go to the store"
* Later, when I open the web app, I will see only "Go to the sto"
* Double-check the Android app. On the Android app it says "Go to the store" and on the webapp it says "Go to the sto"
* Double- and triple-check that both apps have sync'ed and saved properly. Everything says "Saved". Manually sync the Android app by dragging down. Discrepancy persists: On the Android app it says "Go to the store" and on the webapp it says "Go to the sto"
* Now add a new line ("Go to the bank") in the note from the webapp (before making any new modifications from Android). Now it will say on **both** apps "Go to the sto Go to the bank"
* The letters "re" have been lost forever. No "conflicted copy" ever appears.

I will continue trying to figure out a reproduce, but hopefully someone else can confirm this.

**Comment by JaspalSuri** [comment]
Hi @wlevine,

I'm afraid that I haven't been able to reproduce this issue and we haven't received similar reports of this. May I ask:
- What editor you're using?
- What devices are you using?
- Have you signed out of both devices and signed back in?
- Have you cleared the Android app's storage and cache, relaunched it, signed in again, and have still run into the same issue?

**Comment by wlevine** [comment]
I am just using the plain editor.

My Android phone is a Sony Xperia X Compact. I am using the webapp from Firefox on Linux.

I have signed out and cleared my cache as you suggested, and I will report back here if it happens again.

If I get in this state again (Android app shows different contents than webapp, even after syncing), is there anything I can do to help debug?

**Comment by wlevine** [comment]
Haven't seen this in the past week. Will reopen if it starts happening again.
