### ISSUE TITLE
Settings icon is not aligned properly 

### ISSUE THREAD

**Issue by Donnnno** [standardnotes/mobile#345]
I noticed something small, and now I can't unsee it. 🙃
But the settings icon is not aligned properly for me.

![image](https://user-images.githubusercontent.com/31142286/103461823-72c98100-4d21-11eb-9ede-9d5d8c54a81c.png)

I'm using version 3.5.14 right now.

Oh, the dark mode is really nice btw, keep up the good work :)

**Comment by JaspalSuri** [comment]
Hi @Donnnno,

It looks like the gear icon needs to be moved up by 10 pixels; it's currently 86 pixels away from the top of the circle and 67 away from the bottom, but it's centered horizontally.  

Please let me know if you have any additional feedback or questions.

**Comment by Donnnno** [comment]
I'll close this issue because it was fixed a while ago, thanks!
