### ISSUE TITLE
Move "Protected" Label To The Right Of Note Title In All Notes

### ISSUE THREAD

**Issue by landry314** [standardnotes/mobile#356]
The "Protected" label in the All Notes list takes up vertical room when placed above the note title. It could be placed to the right instead to save this room. Most notes have this room to the right anyway! It would be neater this way with every note taking up the same vertical room. It saves scroll time too if there are many protected notes.

**Comment by antsgar** [comment]
Hi @landry314! Apologies for the delay addressing this. In the latest SN release (3.6+), we have moved the "Protected" label to a subtler spot on the left of the note's date. Hope you love this change as much as we do! 🙂 You can check the release notes for 3.6 at https://blog.standardnotes.org/p/99bdaf29-5c7b-47d6-9b09-f5465a315ffe/
