### ISSUE TITLE
Simple markdown preview doesn't show last added text

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#359]
When updating a note with Simple Markdown Editor enabled on ios, and going to preview and back to edit, newly added text is not show. Closing the note and re-opening it shows the last added text. 

Reproduce: 
1. Create a new note
2. Enable Simple Markdown editor (if not enabled by default)
3. Write some text
4. Click on Preview, text is not shown
5. Click on Edit: newly added text is not shown
6. Close note, and reopen note: text from step 3 is shown

Optional 7: add some more text, click preview, click edit, and last added text is not shown.

As you can imagine: very annoying, such a basic functionality not to work.

**Comment by mobitar** [comment]
Thanks for the report; this must be a recent regression.

**Comment by odyon01** [comment]
> 
> 
> Thanks for the report; this must be a recent regression.

I think it's in it for already a long time. I just hoped it would be fixed with some of recent releases. 

One small off-topic question / suggestion: why don't you include relevant release information in the ios-app version history? Now it's quite irrelevant text about 3.5 architecture update, of 2 months ago. Thanks.

**Comment by JaspalSuri** [comment]
Hi @odyon01,

I just wanted to follow up with you on this since the dev team was investigating this issue yesterday. I wasn't able to reproduce this issue on the iOS or Android apps. Do you still encounter this issue?

> why don't you include relevant release information in the ios-app version history

For what it's worth, the subsequent updates have been focused on bug fixes and improvements.

**Comment by odyon01** [comment]
Hi Jaspal, I can’t reproduce it anymore so issue can be closed.

Thanks
