### ISSUE TITLE
[Feature Request] Viewing and editing mode

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/mobile#36]
Good day,

I'm quite enjoying the simplicity and ease of use of the mobile apps and the seemless synchronisation between mobile and desktop! Yet, one feature I would like to see is a distinction between viewing and editing notes. Often I'm not interested in editing a note, but just in reading it. Basically

**Reading mode**
- default when opening an existing note
- no keyboard pops up
- simply drag and to scroll the text
- convert URLs to clickable links
- editing button in bottom right corner similar to the add note button to switch to editing mode

**Editing mode**
- default for a new note
- same as it is right now
- pressing back/up switches to viewing mode, back/up again to get to the main menu

Any thoughts on this?

**Comment by mobitar** [comment]
Hey David, I presume you're talking about the Android app? In which case, I believe the current functionality should not pop open the keyboard when you open a note. Instead, it opens in read mode, then when you tap the body, the keyboard opens. Are you seeing something counter to this? If so, are you able to share a video grab?

**Comment by ddddavidmartin** [comment]
Yes, I am using the Android app. And yes, it does behave the way you describe. I would like it to be more explicit than that though. Because the keyboard still pops up when you try to highlight text or a link.

I have attached two screenshots of how the gmail app changes between viewing an email draft and editing it.

Read mode:
![viewing_mode](https://user-images.githubusercontent.com/710898/35467435-31d11426-0362-11e8-9aa1-32f4bf00d3b9.png)

Editing mode:
![editing_mode](https://user-images.githubusercontent.com/710898/35467434-31986b9e-0362-11e8-97fe-1d8f759c6cc2.png)

In read mode the font size is actually smaller and it is easier to actually read the mail. In editing mode it is more focused on the currently edited section. Also, in read mode you can tap anywhere without it doing anything, and scroll through longer mails quite easily. Interestingly enough it does not actually seem to convert URLs into clickable links, but you can still mark them and copy/share them. From a usability point of view this is pretty neat I think.

**Comment by mobitar** [comment]
Hmm interesting. So what's bothering you is that when you want to highlight something the keyboard comes up?

**Comment by ddddavidmartin** [comment]
Yes, basically that the keyboard pops up and that I do not see as much text as I would like to. Maybe this is clearer with a real world example. I went to linuxconf this week and every day I sat down with my laptop and put together a schedule on what I would like to attent during the day. I stored this in standard notes. During the day I then noticed that it was actually not that easy to read the schedule at a glance from my phone. I feel like this is mostly due to font size and visible whitespace. I have some screenshots again from gmail which I would not want to use for notes, but happens to handle text quite well.

gmail editing mode:
<img src="https://user-images.githubusercontent.com/710898/35478282-166c46f8-042d-11e8-944a-88a796298862.png" width="300">

gmail reading versus Standard Notes reading
<img src="https://user-images.githubusercontent.com/710898/35478283-169cb25c-042d-11e8-9cd8-69c1768d8e95.png" width="300"> <img src="https://user-images.githubusercontent.com/710898/35478284-16cba698-042d-11e8-809d-0fd57291023a.png" width="300">

The view of Standard Notes is very similar to the editing mode in gmail, which works well for editing. Purely for reading a note it helps to have a smaller font. And the keyboard does not pop up when tapping anywhere on the note as well.

Does that make sense?

**Comment by mobitar** [comment]
Got it, makes sense. In iOS, it is idiomatic to do as Standard Notes currently does, which is bring up the keyboard on tap or interaction. Perhaps this is not the case with Android. I like the simplicity of not introducing an additional button, but I will study some Android apps and see what feels right. Worst case we can introduce a setting at some point, if this becomes a big enough problem.
