### ISSUE TITLE
Black Screen hang after login `generating key` use a machine without GMS .

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [standardnotes/mobile#374]
today i buy a new Huawei M6 pad, i want use this app on the device.

i download the apk from release page, install it and login , but when i tap the `sign in` button then after the `generating key ...` show, the app into a black screen , and hang on that .

as well-know, the new Huawei device cannot install GMS (or google play) , dose the broken GMS case this issue ?

**Comment by Lyoko-Jeremie** [comment]
fixed in v3.6.1, thanks for the work ~

**Comment by JaspalSuri** [comment]
We're glad to hear that! We're also pushing another release to the Google Play Store with a fix for another issue, so keep an eye out for that. 🙂

**Comment by Lyoko-Jeremie** [comment]
@JaspalSuri  thank you~ 

i will download the new release from github release page.

**Comment by JaspalSuri** [comment]
> i will download the new release from github release page.

For what it's worth, you can use the [IzzySoft repo](https://apt.izzysoft.de/fdroid/) (which isn't endorsed or maintained by us, more info [here](https://apt.izzysoft.de/fdroid/index/info)), which points to the latest APK's from the [mobile app's releases page on GitHub](https://github.com/standardnotes/mobile/releases) in conjunction with the F-Droid app to access the latest updates quicker.
