### ISSUE TITLE
Opening the settings through the gear icon crashes the app

### ISSUE THREAD

**Issue by landry314** [standardnotes/mobile#375]
I changed the setting for encryption by tapping Disable Storage Encryption and then now I can't even enter settings without the app crashing.

Also, I can open protected notes without a password now. That isn't what is suppose to happen. That is another issue, but, damn, this app just got messy with the new 3.6.1 update.

Standard Notes 3.6.1
Android 11

**Comment by landry314** [comment]
Oh, that IS suppose to happen, you just have very poorly worded descriptions... I am still confused after using this app a lot. I thought you had cleaned up the protection system in this update but, no, it is still super confusing.

**Comment by landry314** [comment]
ok, i realized i can get to settings by tapping on "data not backed up" at the top but going to the gear icon in the menu crashes the app every time. i set it back to enable storage encryption and it works but the settings gear still crashes the app.

**Comment by JaspalSuri** [comment]
Hi @landry314,

Sorry to hear that. A fix for that bug should be available on the Play Store now (or if for some reason it hasn't fully rolled out, later today).

As for the protections - which locks do you currently have set up and what could we make more clear? There was actually an issue (a software regression) with protected notes where it wouldn't ask for a user's passcode after they had unlocked the app, but now it does.

**Comment by landry314** [comment]
ive authored 6 issues in this repository now. issues #338, #339, #341 mainly are about cleaning up settings and improving clarity. i need to learn java so i could contribute more directly to FLOSS apps!

**Comment by landry314** [comment]
fixes with newest update
