### ISSUE TITLE
Scrolling "Flashes" Where You Tap

### ISSUE THREAD

**Issue by landry314** [standardnotes/mobile#376]
When you are trying to scroll the list of notes, where you first tap to start the scroll flashes like it is trying to be selected then switches to scroll instead. It is annoying.

Maybe the sensitivity time for selection is too low?

Standard Notes 3.6.1
Android 11

**Comment by JaspalSuri** [comment]
Hi @landry314,

Thanks for bringing this issue to our attention! I'll put in a request to see if the color of the flashes that appear when a note is selected can be changed to something darker for the dark theme and if the response from the user's input could be adjusted to reduce the overall amount of flashes.

**Comment by landry314** [comment]
yes, i am on dark theme. thanks.
