### ISSUE TITLE
Task Editor - Ability to drag and drop to rearrange

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/mobile#386]
Just switched to Standard Notes from Microsoft To Do and would love to have the ability to drag and drop task items to manually prioritize, without having to switch to code view to copy/paste/manually adjust the order of tasks.

This would be useful for being able to drag and drop to rearrange the order of pinned notes as well, but wasn't sure if needed to submit a separate issue for that feedback.

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, 

You can do this by pressing and holding the checkboxes to select a task before reordering it. 🙂 

https://user-images.githubusercontent.com/44656000/111624546-12d36a00-87a9-11eb-9a7c-77e6f88c6f57.MP4

**Comment by OddHouseGames** [comment]
Many thanks! I would not have thought to long press on the checkbox itself!
