### ISSUE TITLE
Why are my notes on Android only displayed this way?

### ISSUE THREAD

**Issue by gueeme** [standardnotes/mobile#39]
![screenshot_20180215-214226](https://user-images.githubusercontent.com/19538568/36288762-7a82d236-12a3-11e8-9455-dcc3d333812b.png)

**Comment by gueeme** [comment]
Excuse me. It was catching the formatting tags from another source.

**Comment by mobitar** [comment]
For the record, editors are not supported on mobile, so if you edit a note on desktop with the Plus editor, they will appear this way on mobile.

**Comment by leafcutterant** [comment]
Request for re-open.

> For the record, editors are not supported on mobile,

This is no longer the case and I'm having the same issue as @gueeme, albeit selectively.

I have a note which was created with Plain Editor, then it was changed to Plus. This note displays on Android as rich text and the Plus Editor options appear.

Another note I have created with Plus, after Plus was set as the default editor. This note displays as raw HTML, similar to the image the first post.

**Comment by mobitar** [comment]
Editors are indeed now supported on mobile. @leafcutterant in your case you'd just need to click the tags icon in the top right corner and associate the Plus Editor with the note manually in the "Edit With" section, if for some reason it's not automatically picked up. Make sure you're on version 2.3.10.
