### ISSUE TITLE
Search on iOS - lag entering text causing dropped letters

### ISSUE THREAD

**Issue by bschlagel** [standardnotes/mobile#398]
I'm noticing some buggy behavior with the new search and letters getting dropped on text entry. There seems to be a lag that causes multiple keypresses to not always register. For example I'll enter "bookstore" but only "boktre" or "boste" will appear. If I type slowly all letters appear as expected. I'm on iPad Pro with the smart folio keyboard.

**Comment by JaspalSuri** [comment]
Hi @bschlagel, thank you for reporting this issue! I've been able to reproduce the issue and will forward it over to the dev team for review. 🙂

**Comment by JaspalSuri** [comment]
Hi @bschlagel, I just wanted to let you know that a fix for this issue has been applied to the internal beta apps and will make it's way to one of the next stable/public releases of the app. 🙂

**Comment by antsgar** [comment]
Closing this one as it's been fixed on 3.6.8. Of course feel free to reach out if you encounter any other issues 🙂
