### ISSUE TITLE
[Feature Request] iOS UI

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/mobile#40]
Having a bottom navigation bar to hold all four buttons, such which would include the `new` and `filter` button helps a lot as they are used often and can be easily reached.

Borrowing the tag pane from the Android app might help in accessing the tag pane more quickly, as it doesn't cover the entire page and is faster to exit out of, but that's only if the menu/button is kept at the top.

**Comment by mobitar** [comment]
I do like the idea of having a more accessible Filters page, as it's sort of hard to use now. I like the tabs idea. Would require some restructuring though. I don't plan on doing mobile work for a short while, but I'll investigate this again when I'm back in this repo for improvements.

**Comment by mobitar** [comment]
Improved in v3.
