### ISSUE TITLE
Markdown Basic: newline

### ISSUE THREAD

**Issue by affvalente** [standardnotes/mobile#402]
Hi

I have an issue in markdown basic - if I enter this text:
A
A

the preview shows:
A A

(Doesn’t recognise the newline)

IOS 14.4.2
S|N 3.6.6

Everything works well in other editors

thanks
A

**Comment by affvalente** [comment]
I appreciate this is probably the reference/standard, but for S|N this is the only editor that does it this way. 
Could we create an option to use simple line returns, without needing the double space at the end of a line?

https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return

**Comment by affvalente** [comment]
Having looked through markdown-it, which is where this behaviour comes from, this seems to be fixable by enabling the 'breaks' option 

`breaks:       false,        // Convert '\n' in paragraphs into <br>`
[reference](https://github.com/markdown-it/markdown-it/blob/master/README.md)

here as "breaks: true":
```
const markdownitOptions = {
      // automatically render raw links as anchors.
      linkify: true
    };
```

https://github.com/standardnotes/markdown-basic/blob/d828452f3cc47192e8b6bd456d0e0d3005ffda6b/app/components/Home.js#L76

We could consider offering this as an option if you feel strongly this shouldn't be in the default configuration

**Comment by affvalente** [comment]
cc @johnny243 @mobitar 
Linking here the issue I mentioned on Slack

**Comment by johnny243** [comment]
Hi @affvalente! thanks for creating this issue. 

I think this should be the default behavior (if we take into consideration other Markdown Editors).

Feel free to create a pull request!

Thanks 😃

**Comment by affvalente** [comment]
Thanks, done! 
https://github.com/standardnotes/markdown-basic/pull/45
