### ISSUE TITLE
Incorrect two-factor authentication code

### ISSUE THREAD

**Issue by oliversturm** [standardnotes/mobile#408]
I suddenly have a problem that I've had before, but somehow it previously went away by itself. I can't figure it out right now so here's what I did:

* On my Linux machine I had Standard Notes working with the AppImage - not sure which version it was, but I had skipped a few updates. Today I downloaded version 3.6.7 and tried to run it. Oh - I use firejail to isolate SN in a private home directory, and I used a completely new and empty folder this time, basically starting from scratch.
* I was prompted to sign in, so I entered my credentials. Unfortunately I ended up with the error message ***Incorrect two-factor authentication code***. After a few attempts I gave up on this.
* Instead I logged in using a web browser (on the same machine). There was no trouble whatsoever with my credentials and my two-factor code worked fine.
* I was reminded that I also hadn't upgraded to encryption version 4 yet, so I ran that process. No problem. Everything still works fine in the browser.
* Now I checked the installation of SN on my iPhone and predictably found that I needed to sign in again after the encryption upgrade. Unfortunately this didn't work: ***Incorrect two-factor authentication code***.
* I signed out on the iPhone and tried to sign in again: ***Incorrect two-factor authentication code***.
* So now I have two SN apps where I can't sign in again due to the (wrong!) error message about the two-factor code. At the same time I'm signed in with my browser, so I guess that means there's not really anything wrong with the codes. 
* Oh, I did check that both the computer and the phone have the correct time. 
* My iPhone auto-updates, so whatever the latest version is, I should have it. The AppImage is the 3.6.7 I just downloaded today.

Ideas?

**Comment by mobitar** [comment]
We're currently experiencing high latency with our servers. It could be that due to this, it results in a mismatch between the 30 second timer with regards to the 6 digit codes generated. Can you try signing in using a code that is just at the beginning of its 30s cycle?

**Comment by oliversturm** [comment]
Thanks @mobitar - after several more attempts I managed to log in. Good to know for the future that this can happen - so far I've only had trouble like this when my machine had run badly out of time sync.
