### ISSUE TITLE
 version history timestamp bug

### ISSUE THREAD

**Issue by stanuser** [standardnotes/mobile#432]
In version history the date always stays as "December 31 1969 4:00:00 PM" for local session without a remote session to update it. No matter how many entries there are. This applies to both Android and iOS.

**Comment by JaspalSuri** [comment]
Hi @stanuser, thank you for bringing this issue to our attention. I was able to reproduce this issue for a new note. The initial versions had that timestamp but the versions that were saved seconds (after I had added a title to the note) later did not. I'll forward this over for the dev team to review.

**Comment by antsgar** [comment]
Closing this as it's been fixed on version 3.6.9 🙂
