### ISSUE TITLE
[Question] Standard Notes APK update notifcation

### ISSUE THREAD

**Issue by julianfairfax** [standardnotes/mobile#434]
Hi,
If I install the Standard Notes APK from https://standardnotes.org/download will I get some kind of notification when an update is released? Thanks for your help!

**Comment by julianfairfax** [comment]
I just saw the app is back on F-Droid so you can ignore this.

**Comment by JaspalSuri** [comment]
Hi @julianfairfax, the app will not alert users of new updates. For what it's worth, the app on F-Droid is maintained by the community.🙂
