### ISSUE TITLE
[Feature Request] Option to select export location

### ISSUE THREAD

**Issue by engineer22** [standardnotes/mobile#444]
I'm a very happy user and after years of a feature I really wanted, today I finally got it with the new update.

I'm on Android 11, and as you probably know **_android/data/.._** is treated as a application private space for more security. This makes it difficult for users without ROOT to copy/transfer the exported backup, since the directory is no longer accessible via the device UI (I had to connect the device with my PC and browse the directories from there so I can then copy/move the file elsewhere).

I believe it would be great if we had the option to select the export location so we can then backup the file wherever we want.

Thank you for this awesome project!

- Android 11
- Standard Notes v3.6.10
- Offline profile
- No ROOT

**Comment by JaspalSuri** [comment]
Hi @engineer22, thanks for the suggestion! We're aware of this issue and will either provide this option or will export the data to another (usable) path (if possible).

**Comment by engineer22** [comment]
@JaspalSuri I'm thankful. Any location accessible via the UI, really does the job.

A fixed location like /Documents would work fine.

**Comment by JaspalSuri** [comment]
>A fixed location like `/Documents` would work fine.

Thanks for the suggestion! I'll add that to my report.

**Comment by engineer22** [comment]
Thank you for fixing the issue.

**Comment by JaspalSuri** [comment]
On behalf of the dev team, you're very welcome! For anyone else reading this, they decided to go with the `Downloads` folder, as the `Documents` folder wasn't accessible.

**Comment by chaserene** [comment]
the new save location is much more usable, thanks. but it still can't be selected -- do you think it's possible to make it seleactable with a file browser-like location picker?

**Comment by JaspalSuri** [comment]
(cc @antsgar)
