### ISSUE TITLE
[Feature Request] Reduce syncing interval 

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/mobile#45]
Reducing how often Standard Notes syncs notes by saving changes less frequently may make it more battery-friendly, albeit measurably more riskier to use. 

Another added benefits is that within the version history, you won’t end up with countless copies of the note that are saved for every five characters added to it.

**Comment by mobitar** [comment]
I haven't found that it hurts battery too much. It's important that we have however "worry-free syncing". Meaning, you're not wondering, "when will it sync next?" and "has it synced?" It's just always syncing. This way, if you type a quick note, close the app, go on desktop, it's there. If we reduce the frequency, we might make it easier on the machine, but might make it harder on the human.

**Comment by grub-basket** [comment]
I understand, which is why I didn’t ask for it to be the default setting for everyone, just an option within the settings, if it can somehow fit within Standard Notes reasonably strict feature philosophy.

**Comment by mobitar** [comment]
We don't yet have a real settings page on mobile, except for security options. If we do add that (I hope we don't get to that point), this might be a nice place for it.

**Comment by daniele-athome** [comment]
Is there space for a background sync option? For example, if you modify something on your PC and you open the app while not having network coverage, I'd like to already find all the updated notes. Something not too elaborate (from UX point of view I mean), e.g. a preference like "autosync every X hours".
Thanks! (should I open an issue?)

**Comment by mobitar** [comment]
We'd have to look into the cross-platform feasibility of this. But agree could be useful.
