### ISSUE TITLE
Login problem with mobile apps on iOS and Android

### ISSUE THREAD

**Issue by BobWs** [standardnotes/mobile#464]
Hi,
I’m testing iOS 15beta at the moment and I can’t login with the SN mobile app. Tested it on two iOS 15beta devices an iPhone 6s+ and an iPhone XS both can’t login. On other mobile devices with iOS 14 and android everything works fine.

Anyone having similar problems with this?

**Comment by JaspalSuri** [comment]
Hi @BobWs, are you still experiencing this issue? Are you trying to sign into your self-hosting server?

**Comment by BobWs** [comment]
Yes I'm still having problems. But it appears not to related to only iOS 15Beta, none of my mobile apps are working anymore.
When using the webbrowser or the desktop app than everything works fine, I can edit and create notes and they sync with the server.

But the mobile apps on Android an iOS aren't working anymore!

I really don't how this is possible and when it started as I have not change anything.

iOS app version 3.6.20
Android app version 3.6.19
Desktop app version 3.6
Webbrowser app version 3.6.8

This is what I see in the log but it doesn't make sense to me.

```

{"level":"INFO","time":"2021-07-14T09:36:35.269+02:00","message":"{\"method\":\"POST\",\"path\":\"/items/sync\",\"format\":\"*/*\",\"controller\":\"Api::ItemsController\",\"action\":\"sync\",\"status\":498,\"duration\":10.79,\"view\":0.49,\"db\":3.45,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":12751.453474077,\"params\":{\"items\":\"[FILTERED]\",\"sync_token\":\"MjoxNjI0ODc3Mzk5LjM2MzcxNjQ=\\n\",\"compute_integrity\":false,\"limit\":150,\"api\":\"20200115\",\"controller\":\"api/items\",\"action\":\"sync\",\"item\":{}},\"level\":\"WARN\"}","ddsource":["ruby"]}

{"level":"INFO","time":"2021-07-14T09:36:40.508+02:00","message":"{\"method\":\"POST\",\"path\":\"/items/sync\",\"format\":\"*/*\",\"controller\":\"Api::ItemsController\",\"action\":\"sync\",\"status\":200,\"duration\":18.55,\"view\":0.59,\"db\":5.16,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":12756.684578466,\"params\":{\"items\":\"[FILTERED]\",\"sync_token\":\"MjoxNjI2MjQ4MTcwLjUxMTY1Nzc=\\n\",\"compute_integrity\":false,\"limit\":150,\"api\":\"20200115\",\"controller\":\"api/items\",\"action\":\"sync\",\"item\":{}},\"level\":\"INFO\"}","ddsource":["ruby"]}
```

**Comment by BobWs** [comment]
Do you think it is related to the fact that I'm still on `standardnotes/syncing-server:stable`? and not the new `syncing-server-js`?

**Comment by BobWs** [comment]
So I have tested a few things to see what the problem could be.
I have updated the desktop version to the latest (3.8.16) and I had a problem logging in, keep getting an error message that my credentials didn't match.

So I referred back to Desktop version 3.6.8 and I could login normal and all my notes synced from the server.

I tried the same with Android updated to the latest version and I couldn't login. Referred back to version 3.6 and I could login and all my notes synced on Android.

Only on iOS I could not test it because on iOS it is not possible to refer back to an older version. So that is a big problem for me.

I guess this I due the fact that I'm still on the old Standardnotes server.

Any thoughts on how to solve this without the need to update the server?

**Comment by mobitar** [comment]
The latest version of the clients have been updated to rely on the latest version of our server infrastructure. So I'm afraid there's no way to move forward without upgrading your server infra.

**Comment by BobWs** [comment]
> The latest version of the clients have been updated to rely on the latest version of our server infrastructure. So I'm afraid there's no way to move forward without upgrading your server infra.

Thanks for replying!
I will look at upgrading to the new sync-server.

**Comment by JaspalSuri** [comment]
Hi @BobWs, sorry to hear that.

>Only on iOS I could not test it because on iOS it is not possible to refer back to an older version. So that is a big problem for me.

For what it's worth, you can access the previous builds of the iOS betas via the TestFlight app. They will expire within 15 days, though. 

>I will look at upgrading to the new sync-server.

Please refer to [the guide](https://docs.standardnotes.org/self-hosting/getting-started/), especially the article on how to [migrate your database over](https://docs.standardnotes.org/self-hosting/legacy-migration/) to the new setup. Also, please do not use the `Syncing Server JS` repo; instead, use our [`Standalone' repo](https://github.com/standardnotes/standalone). 🙂

**Comment by BobWs** [comment]
> Hi @BobWs, sorry to hear that.
> 
> > Only on iOS I could not test it because on iOS it is not possible to refer back to an older version. So that is a big problem for me.
> 
> For what it's worth, you can access the previous builds of the iOS betas via the TestFlight app. They will expire within 15 days, though.
> 
> > I will look at upgrading to the new sync-server.
> 
> Please refer to [the guide](https://docs.standardnotes.org/self-hosting/getting-started/), especially the article on how to [migrate your database over](https://docs.standardnotes.org/self-hosting/legacy-migration/) to the new setup. Also, please do not use the `Syncing Server JS` repo; instead, use our [`Standalone` repo](https://github.com/standardnotes/standalone). 🙂

Thanks for reaching out!
I have manage to successfully upgraded my Standardnotes syncing-server to the new version, and I also successfully migrated all my users notes to the new server/database.
