### ISSUE TITLE
[Feature Request] Word/character count

### ISSUE THREAD

**Issue by FiveYellowMice** [standardnotes/mobile#47]
I use Standard Notes to write article drafts. For writing, I found sometimes I want to see how much I have written. But right now SN doesn't show this information, so everytime I want to know the amount of content I have written, I need to copy everything elsewhere in order to count them. So it would be ideal to have a word/character count in the menu.

The extension Action Bar does this on desktop, but mobile apps aren't going to get extension support anytime soon, and the concept of an Action Bar doesn't seem to fit on mobile, either.

**Comment by mobitar** [comment]
The mobile apps are currently complete as is, and short of getting extensions, won't be receiving new features, generally speaking. So can't make any promises on this.
