### ISSUE TITLE
iOS App: Keyboard overlaps with last text line in flight mode if "unable to load" banner is displayed

### ISSUE THREAD

**Issue by Anthanos** [standardnotes/mobile#470]
When writing longer notes in flight mode on the current iOS App on iPhone SE 2020 at some point the last line is overlapped by the keyboard. This makes it very inconvenient to continue writing. As soon as flight mode is disabled and the "unable to load" banner below the top navigation bar disappears, the note can be edited as usual. I cannot share the screen due to the confidentiality of the note, but hope you get the issue and fix it. Thank you.

**Comment by JaspalSuri** [comment]
Hi @Anthanos, thank you for reporting this issue! I was able to reproduce it and will forward it over to the dev team for review. 🙂
