### ISSUE TITLE
Does not appear in Android's Share menu

### ISSUE THREAD

**Issue by AdKiller** [standardnotes/mobile#473]
I do not see Standard Notes in Android's Share menu when trying to share a text from other apps. Is it just me?

Android 8.0.0
Samsung Galaxy S7
Standard Notes v3.6.22

**Comment by jbeldia** [comment]
Hi there, I'm afraid it's really not on the share menu at the moment, but it is part of our long term plans, ideally before v4! Please see this [previous post](https://github.com/standardnotes/mobile/issues/245) as well.
