### ISSUE TITLE
Having trouble with the android app built

### ISSUE THREAD

**Issue by creatvty** [standardnotes/mobile#474]
Hey, 

so I'm trying to build the android app myself but I'm having trouble doing so. The current Readme.md has barely any info about actually building the app. I tried `yarn android-prod` but it seems this is only for running it connected to the computer.

In an older version of the Readme.md I found the command `cd android && ./gradlew assembleRelease` which seemed to do the trick but it is spitting out a "1.0" version where I'm not sure if this is only a minor issue or pointing to something more serious. Is it even possible to build the app on your own?

When I do Install the app on my phone it also shows me 1.0 but the bigger Issue that when I try to connect to my local instance it stays stuck on "Generating Keys".

I hope someone can help.

Kind regards
Daniel

**Comment by JaspalSuri** [comment]
Hi Daniel, while we currently don't provide dedicated technical support for building the apps or self-hosting, is there anything in this [discussion thread](https://github.com/standardnotes/mobile/discussions/427) that might help?

**Comment by creatvty** [comment]
Well, not really apart from that it seems really complicated now and it doesn't actually cover building this app but this persons on approach. It would help me to confirm that what I did is actually the correct way of building the app and is working correctly when done that way. Then I just have to figure out why it gets stuck on "Generating Keys"

**Comment by creatvty** [comment]
Closing this, got it to work after cloning the repo again
