### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#5]
This was discussed in the [old repo](https://github.com/standardnotes/android/issues/60) for the Android version and I hope it is safe to bring it up now. Would be amazing if this could actually make it before the launch of the app but I would like to know if it is at least up for consideration.

With regards to how to approach this, could it be possible to go with support for all the standard tags but only by manually entering them (asterisks or underscores for bold or italic, etc.) instead of offering different editors with actual buttons to format text the way that the desktop client does? The UI would remain cleaner this way but the ones who do need and use it would be free to do so.

Rendering could be handled with tabs (edit and view) at the bottom or top of the note view.

**Comment by mobitar** [comment]
I'm optimistic about Markdown with this app. This codebase makes it a lot easier to add stuff like this. But it definitely won't be in the initial release. The initial release is already big enough that I first want to establish base-line stability before adding complex features like this. But I don't imagine it will be too long after that I'll begin looking into incorporating editors.

**Comment by OriginalFannibal** [comment]
I'm so, so grateful. I dream of the day when I can see Markdown :)

**Comment by OriginalFannibal** [comment]
What do you think of using the context menu to format text the way that WhatsApp does?  

![screenshot from 2017-10-05 14-39-52](https://user-images.githubusercontent.com/20235646/31219619-8639caac-a9db-11e7-821b-24bfc9ecfe65.png)

This would be a pretty elegant implementation.

**Comment by lokesh-krishna** [comment]
Just wanted to add this to the discussion. When Markdown makes it, what's the plan for handling the default view when opening a note? It would be nice if new notes opened in the edit view while existent notes opened in a preview view. [Tabs](https://material.io/components/android/catalog/bottom-navigation-view/) could be used to switch between the two.

**Comment by mobitar** [comment]
Haven't given it any thought yet. Will revisit once I begin working on it.

**Comment by DreamFlasher** [comment]
This is done! \o/ Thank you @mobitar this is so amazing, thank you for you great work! :)

**Comment by mobitar** [comment]
Thanks @DreamFlasher, glad you're enjoying it!

**Comment by mobitar** [comment]
Editors and Markdown are available on mobile since ~v2.1.
