### ISSUE TITLE
Some strings appear trimmed on Android

### ISSUE THREAD

**Issue by BuriedInTheGround** [standardnotes/mobile#529]
## Description of the issue

As the title says, in the Android app, some strings appear trimmed. See the indicated areas in the screenshot below.

![standard-notes-android-issue](https://user-images.githubusercontent.com/26801023/149618436-da11a99b-1afb-4753-8329-93037077d074.jpg)

- "All" instead of "All notes"
- "Pinne" instead of "Pinned"
- "Editing" instead of "Editing Disabled"

Note that the same issue appears even when logged in.

## What I tried to do

I already tried the following, but nothing changed.

- Change the app theme
- Sign out of my account
- Clear the app cache
- Clear the app data

## Environment
- Android version: 10
- Standard Notes app version: 3.9.12 (3000323)

**Comment by moughxyz** [comment]
Hmm, any chance your device is a OnePlus? I've seen this issue before for this manufacturer.

**Comment by BuriedInTheGround** [comment]
Indeed, it is!

I've recently changed the system theme from settings, and it seems that the font automatically changed too! So, yeah, I can confirm that the culprit is indeed the "OnePlus Slate" font, it is not the first time is encounter this issue when it comes to React Native. :facepalm:

I'm closing this issue as it's not Standard Notes fault.
