### ISSUE TITLE
F-Droid package issues

### ISSUE THREAD

**Issue by hueyyyyyyyyy** [standardnotes/mobile#532]
Version 3.9.6 (3000323)
F-Droid 1.13.1-16 
CalyxOS 2.11.0
Google Pixel 4a

After upgrading my overdue account to the Pro tier, I changed some notes to use the code editor in the web client. 
Upon trying to load those notes on my phone I got an error "Extension installed incorrectly" and no content visible.
Several other editors were also broken, (but not the Secure Spreadsheets.)

Tried re-installing, clearing cache, removing and re-installing extensions on desktop.

Fixed by uninstalling the F-Droid package (3.9.6) and manually installing 3.9.12 from the apk hosted at github,
(It sure would be nice to have a gpg verification process for these github apks.)

**Comment by moughxyz** [comment]
Yeah the new extensions system requires up to date clients on all platforms. The Fdroid package is third-party maintained so I'm not always up to date on its status or version.

> It sure would be nice to have a gpg verification process for these github apks

I have this in mind as well 👍

**Comment by proletarius101** [comment]
Fixed in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10602

**Comment by proletarius101** [comment]
@hueyyyyyyyyy Can you please git tag your releases such that we can automatically update on fdroid side, rather than lagging so long? Thanks
