### ISSUE TITLE
[android] default font size question

### ISSUE THREAD

**Issue by ElTopo** [standardnotes/mobile#54]
Hello,

I am testing the free Android version of Standard Notes from Google Play Store. One thing I immediately notice is the default font size is too small for me to read comfortably. 

Is there any plan to offer bigger font sizes for plaintext notes? 

Thanks.

**Comment by ElTopo** [comment]
@mobitar Thanks for your reply, however, I did try bigger system font size, unfortunately, it caused problems with some other apps, such as incorrect UI buttons, truncated strings.

**Comment by mobitar** [comment]
Ok, thanks for the heads up. I'm hoping we can add a display settings menu in the app, but no such feature currently.
