### ISSUE TITLE
Sort directions ascending and descending

### ISSUE THREAD

**Issue by rdai** [standardnotes/mobile#55]
Hi,

Thanks for the great product. I am using it daily now. If I missed this I apologize but there doesn't seem to be options to sort either ascending or descending but just one direction. I have a diary that I label with yyyy-mm-dd so the default sort always put the latest at the bottom when I would like to have it on top. This is probably a feature that is missing from all versions and would be nice to have.

Thanks

**Comment by mobitar** [comment]
Hey @rdai, good point. No such way to do this now, but perhaps we can add this in a future update.

**Comment by mobitar** [comment]
Reverse sorting now available in v3, via the Settings page.
