### ISSUE TITLE
Changing the theme crashes the app

### ISSUE THREAD

**Issue by PlugaruT** [standardnotes/mobile#56]
I'm using the application on a phone with Android 8.1. The problem is that when I'm changing the theme, the app crashes. I don't know if this is a feature or a bug, but if this should tell the user that the application should be restarted in order to apply the theme then this is not a good way to do it :)

**Comment by PlugaruT** [comment]
I'm using OP 5 with Android 8.1. The app version is 2.1.36. The steps are Settings -> Apply the theme -> The dialog that the app has crashed appears.

**Comment by mobitar** [comment]
And do you know if the theme you're choose was recently installed? Or installed a long time ago? And does it happen on all themes, or a particular one?

**Comment by PlugaruT** [comment]
I only have the Solarized Light installed and it crashes if I switch between the default one and the one installed.

**Comment by mobitar** [comment]
Should be fixed in 3.0.0 release.
