### ISSUE TITLE
iOS: 3rd-party editors not loading the note content when using a dark theme

### ISSUE THREAD

**Issue by stripedgoat** [standardnotes/mobile#564]
For some reason, when I use a dark theme (whichever it is - doesn't matter), the content of all of my notes are not displayed when I open them. 

If I switch the editor to the default editor, the content appears. 

Another way to "fix it", is picking a light theme. Then it works fine all the time... 

Another behavior I noticed: If I hold down on a dark theme and redownload it, then the content of my notes re-appear, UNTIL I completely close the app (from the app drawer). Then it bugs out again, and stays that way until I either pick a light theme or redownload my dark theme. 

I tried re-installing the app several times, but it didn't help unfortunately.

iOS 15.3.1, Standard Notes 3.12.0 (114)

**Comment by stefan-yas** [comment]
Thanks for the report @stripedgoat! Issue is not replicable for us on the team at the moment, but we'll keep a lookout on any other reports of it.

**Comment by stripedgoat** [comment]
Hmm, interesting. Any suggestion to solve this? Perhaps I should open a new account?

**Comment by stefan-yas** [comment]
Could you send an email to help@standardnotes.com for my team to look into your account? Perhaps there's something up with it behind the scenes, so would be good to check before making a new account. Feel free to link this GitHub thread.

**Comment by bejucoo** [comment]
I have the same issue but in Android. I'm trying to use the Indent Editor but it doesn't work with any dark theme. I'm using the v3.14.1 of the app.

**Comment by stripedgoat** [comment]
Finally someone else reported this as well. I'm quite certain that this is a common issue, but people aren't reporting it, or they aren't using a 3rd-party editor so the bug doesn't appear in their case. I've gone as far as resetting my phone and erasing all data, but that didn't solve this either. It's a bug in the app.

**Comment by eminp** [comment]
I don't know if this is relevant or not but here is an error message on android.

```
W/System.err(4147): 	at com.standardnotes.sntextview.SNTextView.setHandlesColor(SNTextView.java:222)
W/System.err(4147): 	at com.standardnotes.sntextview.TextViewManager.setHandlesColor(TextViewManager.java:63)
```

**Comment by Tellervo89** [comment]
I face the same issue on Android currently.

**Comment by stripedgoat** [comment]
They don't really seem to care about it. It's still present and going strong 😆 The 3rd-party Scratch Editor seems to be working with the default Dark Theme, so I settled with that. But it's also buggy with other themes that are updated to the new system...

**Comment by Tellervo89** [comment]
I am dependent on a highlighter tool, so Scratch won't do it, unfortunately. Weirdly, the Standard Notes Editor's are not working either in my case (e.g., Markdown Pro, Markdown Minimalist, etc.). 

All editors are working with the Solarized Dark Theme from Standard Notes. However, when I cloned the theme, without applying any changes to the code, all editors stopped working again.

**Comment by stripedgoat** [comment]
Yeah, it's acting really funky... Let's hope someone from the dev team realized this is an issue and needs to be fixed.
