### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by pinpontitit** [standardnotes/mobile#568]
Hi
How come the Links URL aren't clickable yet ?
I tried searching in the other issues or in google search to check if it was explained by the Standard notes team but I didnt find anything.

Its so annoying to always have to copy and paste links in my browsers.

Has it something to do with the encryption ? Hyperlinks arent enough protected or something like that ?

I'm using android app, and normal plain text, I'm not using special markdown editor.

Thanks, and sorry if its already a stubborn topic, but I swear I looked for it and didnt find.

**Comment by JonCStout** [comment]
I think this is expected behavior for the plain text editor.  Clickable links are a form of rich text, mark down.

**Comment by pinpontitit** [comment]
Hi
Ok so I guess I'd change my enchancement to : "add possibility to do cliclable link with plain text", or if thats not possible "allow markdown in free plan and in android".

**Comment by stefan-yas** [comment]
This is expected behavior with the Plain editor. Markdown and Rich Text editors do require a subscription in Standard Notes and if you're interested, feel free to [have a look at the plans here](https://standardnotes.com/plans).
