### ISSUE TITLE
IOS version 3.12.0 (114) is adding arbitrary characters in blank fields.

### ISSUE THREAD

**Issue by 1lgatto** [standardnotes/mobile#572]
I'm using Scratch Editor and every time after I close a note, and open it again I see one "Â" in every blank field of the note. See ss below:
![image](https://user-images.githubusercontent.com/77030966/158018550-6f05e06d-1f17-44b3-85dd-fb87098c1a8f.png)
![image](https://user-images.githubusercontent.com/77030966/158018556-1ddcb9cd-fcd4-45c0-8933-e94b10533cf7.png)

It's very frustrating and I have noticed it a couple of weeks ago or more.

**Comment by stefan-yas** [comment]
Please try opening an issue where the editor maintainer can take a look - seems like [this would be the place](https://github.com/dylanonelson/sn-scratch-editor).

**Comment by 1lgatto** [comment]
https://github.com/dylanonelson/sn-scratch-editor/issues/36#issuecomment-1133601820

The bug is back starting with the recent version 3.20.0
