### ISSUE TITLE
Google Play Release crashes on launch on Motorola Moto G31 with Android 11

### ISSUE THREAD

**Issue by rogerssam** [standardnotes/mobile#575]
Firstly, thank you all for your work on a superb app!

**Describe the bug**
The Google Play version of SN (3.12.0) crashes immediately on app load on my mobile device. Note this does not occur on the manually installed APK.

**What I have tried**
I have tried restarting the device. No change.
I have tried uninstalling and reinstalling from Google Play. No change.
I have tried granting storage view permissions in the app info screen, before starting the app. No change.
I have installed the APK directly from [the releases page](https://github.com/standardnotes/mobile/releases/tag/3.12.0). This was successful in allowing the app to start and function as expected,

**To Reproduce**
1. Install app from Google Play
2. Tap on app to start
3. Immediate crash

**Device Information**
Motorola Moto G31 (Australian version)
Android 11 software version RRWD31.Q3-26-73
Kernel Version: 4.14.186+ (1 December 2021)
Security update version: 1 December 2021
Google Play Store version: 1 February 2022
ThinkShield for mobile version 01.01.000

**Expected behavior**
App starts without crashing.

**Logs**
Attached below. I have additional log information if required.
[android-debug-short.log](https://github.com/standardnotes/mobile/files/8324082/android-debug-short.log)

**Comment by rogerssam** [comment]
Wow, thanks for the speedy response! Yes, I got a new phone in the last few days, and SN was installed as an app I had installed from the previous device (so was a backup).

**Comment by moughxyz** [comment]
Ah, excellent, this means we're on the right track. So the fix will come from a major React Native upgrade (0.67.4 => 0.68); I've read comments that 0.68 fixes the issue, but 0.68 is not yet [released](https://github.com/facebook/react-native/releases). So we're waiting on that.

In the meantime, head over to your Android storage settings, and clear data for this app. Then I think you should be good.

**Comment by rogerssam** [comment]
Wonderful, clearing data does indeed fix the Google play issue, though the manual APK install was working fine too.
Thank you again for your fast responses and help with the problem. I'll close this issue now.
