### ISSUE TITLE
[BUG] crash on start since update

### ISSUE THREAD

**Issue by SnowZucc** [standardnotes/mobile#585]
Bug description : the app is not starting since the latest update (3.14.0)

Device infos :
Poco X3 Pro (M2102J20SG) vayu

Android 11, Lineageos V18.1 (Update of 21/03/2022)

Build number : lineage_vayu-userdebug 11 RQ3A.211001.001 eng.root.20220407.063409 dev-keys

**Comment by stefan-yas** [comment]
Please [sideload the 3.14.1 version](https://github.com/standardnotes/mobile/releases/tag/3.14.1), which should fix the crash on launch issue.
