### ISSUE TITLE
[Android] Text selection handles do not reflect theme colors

### ISSUE THREAD

**Issue by OriginalFannibal** [standardnotes/mobile#6]
Presently, the text selection handles use the default teal color. This is the color used with the default theme as well as all the other themes. 

![screenshot_20171005-141711](https://user-images.githubusercontent.com/20235646/31218752-ec9ab570-a9d8-11e7-9e4b-890a5eea7278.png)

It is possible in Android to make these handles reflect the color of the theme. Here is a screenshot from Signal displaying what I'm talking about.

![screenshot_20171005-141801](https://user-images.githubusercontent.com/20235646/31218993-99899a9e-a9d9-11e7-8bff-9d051f0af5de.png)

This may be of some use: [How to change textSelectHandle color for an EditText](https://stackoverflow.com/questions/41311044/how-to-change-textselecthandle-color-for-an-edittext).

**Comment by mobitar** [comment]
Good catch, I'll look into this.
