### ISSUE TITLE
Can't change note type after 3.20 update

### ISSUE THREAD

**Issue by catwithbanana** [standardnotes/mobile#619]
After the 3.2 update trying to change the note type on mobile does nothing. Tapping on Markdown Minimist or Markdown Pro or any other options produces no changes and closes the menu. When I re-open the menu it shows that it has reverted to Plain Text (no matter what the type was before).

This means a large portion of the functionality is currently unavailable on mobile. I am able to start new notes of any type on mobile, but can't switch once the type is designated.

I'm on a Pixel 5 running Android 12.

**Comment by moughxyz** [comment]
Thanks for reporting, I can replicate this the second time around. We'll get this fixed asap.
