### ISSUE TITLE
When searching can a "new page" be suggested with the title being the search term?

### ISSUE THREAD

**Issue by 0xCMP** [standardnotes/mobile#64]
It'd make life easier if there were an option to treat the search term as a possible new page like nvAlt does. Searching for a term that brings back nothing should make it easy to make a page for that.

For instance: search for `python` and either nothing shows up (give way to make that page), something which isn't what you meant shows up (e.g. contains the word, but the title isn't the same so give item which creates a new page), or the page you meant appears and you can now go back to editing it.

Another awesome feature of nvAlt is the support for the `[[search term]]` syntax which made linking between notes very easy since all it did was populate the search box and select any note which matched the text in the title exactly.

**Comment by mobitar** [comment]
Hmm..I agree it would be a useful feature. But then again, it's just another feature. I'd say this is unlikely in all honesty, unless we find a way to do it with extensions.

**Comment by 0xCMP** [comment]
The issue being though that I think we can't create an extension yet to do this on mobile. Also I'm not sure, but from the docs I don't think you can make an editor which "searches" after clicking specific kinds of links. Right?

**Comment by mobitar** [comment]
Oh, mobile. Well, you're right that mobile will most likely remain true to its core, but on desktop, the whole searching functionality can be outsourced to an extension at some point (once the architecture is built for it).
