### ISSUE TITLE
Can't seem to build project - Windows 10

### ISSUE THREAD

**Issue by camdit** [standardnotes/mobile#69]
I am trying to build the project following the instructions. Simple enough, but I am running into build errors. 

Here are the steps and my setup:

1. using git version 2.17.1.windows.2 I clone the repository and update submodules:
git clone https://github.com/standardnotes/mobile.git
cd mobile
git submodules update --init

2. using npm version 6.2.0:
npm install
(18 vulnerabilities found, I do not fix them)

3. using react-native-cli: 2.0.1 | react-native: 0.48.4:
react-native run-android
SDK=> 26.0.2
NDK=> r17b

This last step errors our failing on the dependency for fbjni

I repeated the steps with NDK => 10e 
This errors out at the final stages of the build, I am re-running that now to see where it was exactly.

Can someone that has successfully built this in Windows describe their build environment?

Thanks!!

**Comment by camdit** [comment]
Sorry for the long response time. I don't remember the error. I ended up using 10e, then I had to run gradlew from the react-native-aes folder, then it finally compiled. But I ran into to many errors while it was running on the emulator. I finally gave up and tried android-classic. It seems to work fine.

**Comment by mobitar** [comment]
Android classic will not support the newer versions of the encryption protocol. So only accounts created **before** June 2018 will work.

**Comment by camdit** [comment]
It compiled fine and I am using it. I will keep this in mind if it suddenly stops working.
