### ISSUE TITLE
[Android] Color section titles in settings with primary/accent color

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#7]
Presently, the section titles in the settings use a grey color across themes. Material Design apps typically color the section titles within settings with either the primary or accent color. Here's what things look like in Standard Notes presently:

![screenshot_20171007-081846](https://user-images.githubusercontent.com/20235646/31304105-0fe2dc60-ab0a-11e7-956c-65f1ed9fbb99.png)

Here are screenshots from two different apps to show what I'm talking about:

First is Unit Converter Ultimate, which uses the primary color for the section titles:

![screenshot_20171007-075536](https://user-images.githubusercontent.com/20235646/31304072-14c5decc-ab09-11e7-8b88-f8c314df511a.png)

And here is Phonograph, using the accent color:

![screenshot_20171007-080829](https://user-images.githubusercontent.com/20235646/31304073-31349436-ab09-11e7-8f95-7c55988641df.png)

As an added advantage of taking this approach, you can drop the divider that's beneath the section title and reduce the visual clutter. This is something that the [Material Design guidelines](https://material.io/guidelines/components/dividers.html#) recommend, minimising the use of full-bleed dividers. Additionally, you might've noticed that those apps also drop the full-bleed divider that follows the last entry in a section as the next section title provides sufficient visual distinction and I request you to take that too into consideration.

**Comment by mobitar** [comment]
Thanks, fixed.
