### ISSUE TITLE
Android: unable to copy text from a locked note

### ISSUE THREAD

**Issue by jeremyj** [standardnotes/mobile#70]
On Android 7.0 to copy text from a locked note you have to open the note, unlock it, go back to the notes list, reopen the note and finally copy the text (and eventually re-lock the note).
A very lengthy workflow.
It would be nice if you were able to copy directly from the locked note.

**Comment by mobitar** [comment]
Agreed, an annoying problem. Currently a limitation of how the Android SDK handles disabling text fields (disables copying as well). Will need to find a workaround.

**Comment by mobitar** [comment]
The latest 3.0.2 release addresses this issue.

**Comment by jeremyj** [comment]
Fantastic! Thank you very much :-)
