### ISSUE TITLE
On android self hosted server can become unreachable by app

### ISSUE THREAD

**Issue by Flylowguy** [standardnotes/mobile#74]
I am unsure where the cause of this issue is, but I've been running into a problem with the android app. I'm self hosting the standard files server and my desktop instances haven't had a single problem. The mobile app occasionally gets out of sync and will fail to download or upload new notes. After that, I try logging out of the account, but am unable to log back in. The app presents a generic error message. I'm also unable to register a new account. I can fix the issue at this point by first logging into the standard sync server, then logging out, and re-logging into my self hosted instance.

Any thoughts on what might be going wrong? Perhaps the app is holding onto some state and not properly releasing it on logout?

**Comment by mobitar** [comment]
Hard to say here without more info whether this is a server issue or a client issue. Have you looked into your server logs for anything?

Server logs can be found in:
sf/logs/production.log
/opt/nginx/log/error.log

Also, what host are you using for your server? Some free-tier servers automatically sleep after small periods of inactivity, so you may be seeing a timeout issue.
