### ISSUE TITLE
Android Studio 3.1.4 adaptations

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#75]
I had to do a few steps to get the project to compile with Android Studio 3.1.4 (from Android Studio 3.0, which is what master is based on)

1. Update gradle-wrapper.properties `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`. 

2. Update android/build.gradle:

   From: `classpath 'com.android.tools.build:gradle:3.0.1'`
   To: `classpath 'com.android.tools.build:gradle:3.1.4'`

3. Install android-ndk r10e from https://developer.android.com/ndk/downloads/older_releases. Update android/local.properties:

```
ndk.dir=/Users/me/Library/android-ndk-r10e
```

(Use the path where you extract the ndk download)

I might push these updates to master, but need to do more testing.

**Comment by khaledBou** [comment]
currently in my Mac i set ndk.dir like this :
ndk.dir=/Users/khaled/Library/Android/sdk/ndk/21.0.6113669
21.0.6113669 is my current NDK version
