### ISSUE TITLE
iOS app: tags are not saved to new note after quitting and reopening the app

### ISSUE THREAD

**Issue by pvogenthaler** [standardnotes/mobile#77]
Steps to Reproduce:
- Filter by a tag
- Create a new note (filtered tag will be automatically added to that note)
- View either that the note has the tag in the list of notes

![image from ios 1](https://user-images.githubusercontent.com/19457998/44165520-988d5700-a08e-11e8-9f83-a100d8d0c3eb.jpg)

- Quit the app and reopen
- View list of notes
- Expected: New note should exist with tag
- Actual: New note is there but is missing the tag

![image from ios](https://user-images.githubusercontent.com/19457998/44165546-a6db7300-a08e-11e8-9fe5-751b41498012.jpg)

Note: Tags work as expected when adding the tag via the "Manage" options

If I have some time this weekend, might look into the issue.

**Comment by mobitar** [comment]
Oh no, good catch! Thanks for the detailed repro steps. Will get this fixed in next release.
