### ISSUE TITLE
Desktop/mobile Color Inconsistency

### ISSUE THREAD

**Issue by infosisio** [standardnotes/mobile#79]
I started using the mobile version and I love it, I was just wondering why red there and blue everywhere else (desktop/web/site) ? UX household names such as spotify make sure to keep it consistent.

**Comment by mobitar** [comment]
This question comes up often. The short answer is that blue looks good on desktop but too default on mobile. And red looks good and intimate on mobile but too "dangerous" on desktop.

**Comment by infosisio** [comment]
@mobitar I get that but the answer may perhaps be in some user metrics. Have you tried to gather some for this particular point ?

**Comment by aadilayub** [comment]
I agree. The inconsistency is jarring. The problem is not with red or blue but in the inconsistent experience between the two apps.

**Comment by mobitar** [comment]
Please see here: https://standardnotes.org/help/49/why-is-the-app-icon-different-from-the-brand-icon

**Comment by mobitar** [comment]
Blue by default in mobile v3.
