### ISSUE TITLE
Android ReactAndroid repositoryUrl changes

### ISSUE THREAD

**Issue by mobitar** [standardnotes/mobile#82]
There's a bug with the version of React Native we're using, and upgrading is not trivial, so here are the instructions to fix this.

If you see an error along the lines of 

> Could not get unknown property 'repositoryUrl' for project ':ReactAndroid' of type org.gradle.api.Project.

1. Open `node_modules/react-native/ReactAndroid/release.gradle`

2. Replace

```
def getRepositoryUrl() {
    return hasProperty('repositoryUrl') ? property('repositoryUrl') : 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
}

def getRepositoryUsername() {
    return hasProperty('repositoryUsername') ? property('repositoryUsername') : ''
}

def getRepositoryPassword() {
    return hasProperty('repositoryPassword') ? property('repositoryPassword') : ''
}
```

with

```
def getRepositoryUrl() {
    return findProperty('repositoryUrl') != null ? property('repositoryUrl') : 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
}

def getRepositoryUsername() {
    return findProperty('repositoryUsername') !=null ? property('repositoryUsername') : ''
}

def getRepositoryPassword() {
    return findProperty('repositoryPassword') != null ? property('repositoryPassword') : ''
}
```

**Comment by infosisio** [comment]
@mobitar I made that change and created a virtual Android device and I am still getting the same error when trying to sync. Am I missing something ?

**Comment by mobitar** [comment]
Hmm not sure. Can you post the code in that file on line 17?

**Comment by infosisio** [comment]
@mobitar 
line 17:
def thirdPartyNdkDir = new File("$buildDir/third-party-ndk")
entire file:
https://0bin.net/paste/mWsh9BSHvlYdWEbT#s6uJ+T8NKe8+NoMgjb4mvumE5qw2YLd3PDZQNvJqdS6

**Comment by mobitar** [comment]
Hmm it might be related to missing ndk. Try following step 3 from this issue: https://github.com/standardnotes/mobile/issues/75

**Comment by mobitar** [comment]
These all look like warnings. Are you able to compile?

**Comment by infosisio** [comment]
@mobitar The emulator opened the phone but I got:
Failed to execute aapt
https://0bin.net/paste/qGnr2MJuYhB0jIBi#WEacPgZQ5XH2iGe3uaVvQb3F36c4jQfE9gCas5naiM3

**Comment by mobitar** [comment]
Haven't seen this error before. Try googling and see what you can find on this.

**Comment by infosisio** [comment]
@mobitar I think I will skip trying to build this for now. I only wanted to do it to try things relevant to the issue with not being able to scroll to the top. Is it desired to hide the keyboard when the user scrolls up ? If the keyboard is hidden, the user is able to scroll to top.

**Comment by infosisio** [comment]
@mobitar I just managed to have it build but I get an error on the phone "Could not connect to development server" - any ideas ?

**Comment by infosisio** [comment]
@mobitar I managed to build the apk but the scroll issue I tried really really hard and I can't fix it.

**Comment by mobitar** [comment]
v3 uses latest version of RN.
