### ISSUE TITLE
[Feature request] Add filter option to select all notes without a tag

### ISSUE THREAD

**Issue by brycx** [standardnotes/mobile#85]
It would be very useful having a filter option that would only display notes that don't have a tag. I sometimes create notes and forget to set a tag. Currently I have to search through all notes to locate the ones not tagged.

This also applies to the desktop application, but since you try to avoid new features, I first wanted to know if this would be something that could be considered. If it is, I'll happily add a issue to the desktop repository.

**Comment by mobitar** [comment]
You can do this via Smart Tags: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes

**Comment by brycx** [comment]
@mobitar Thank you, that's very helpful!

**Comment by mobitar** [comment]
Smart tags are now available in v3 mobile.
