### ISSUE TITLE
abillity to create direct shortcuts to notes

### ISSUE THREAD

**Issue by peterrus** [standardnotes/mobile#86]
Just an idea: maybe implement a way of creating shortcuts to notes you need to access quickly (shoppinglists, GTD lists, or just all pinned notes). I know this is not a native app but something along these lines is possible in android via https://developer.android.com/guide/topics/ui/shortcuts/

I know we have pinned notes. But they are not easily enough accessible (imho). For example: I opened the view for some random tag. I then close the app. Now I want to show my pinned notes: I have to openen the hamburger menu, scroll to 'all notes' and tap it. Which takes a lot of scanning the sceen (especially if you have lots of tags). 

Just throwing it out there ;)

**Comment by mobitar** [comment]
This would be interesting. So far I'm trying to avoid extra-convenient features, as they are endless in scope, and new ones are introduced with every iOS and Android update. I know what chasing after these feel like, and I also know they can improve one's life by 2-3%, but it tends to get out of control from a development perspective. Not totally against it, but just likely to take my time on features like these.

**Comment by peterrus** [comment]
Completely understand that! Rereading my initial post I think I am more or
less proposing a way to quickly open all your pinned notes without
scrolling and scanning through the hamburger menu. Maybe a button
next/close to the hamburgermenu that directly opens a view of all pinned
notes?

**Comment by mobitar** [comment]
Wait wouldn't this just be clearing your filters? So if you are in a tag, open hamburger menu, press "Clear" in the tags area, that would reset to your default view, at which point, you would just see your pinned notes by default. Do you mean something else?

**Comment by peterrus** [comment]
There is no clear button in the hamburger menu (it is in the tags/options
view for a specific note). But I can set the the hamburgermenu to 'tags:
all notes' (see screenshot). Which feels like a bit too much fiddling (in
my opinion)

Just looking for something to quickly open my GTD list, which I tend to
open multiple times a day, everyday.

Just trying to optimize the UX at this point ;) no pressure. Maybe someone
else comes up with a clever solution.

**Comment by mobitar** [comment]
There's no "Clear" button? I wonder if I added that for iOS only. That would be strange. I'd have to double check.

**Comment by peterrus** [comment]
![screenshot_20180926-161804__01](https://user-images.githubusercontent.com/1117858/46087240-2c803180-c1aa-11e8-938b-cff8d3268db7.jpg)

**Comment by peterrus** [comment]
![screenshot_20180926-163552__01](https://user-images.githubusercontent.com/1117858/46087319-5afe0c80-c1aa-11e8-94d2-a7c79834988b.jpg)
