### ISSUE TITLE
Feature request: directories for notes

### ISSUE THREAD

**Issue by nutpantz** [standardnotes/mobile#87]
It would be very nice if there were directories to hold notes (and other nested directories to hold more notes).
It would make organizing, sorting and storing a large amount of notes much easier.

**Comment by mobitar** [comment]
For mobile, this is unlikely. We're just going to keep it as a flat tag hierarchy. For desktop/web, we have the [Folders extension](https://standardnotes.org/extensions/folders). However, maybe some day that extension itself will work on mobile. At least on tablets. Maybe.

**Comment by nutpantz** [comment]
I would think it would work better on mobile than desktop or tablet, when screen real estate is at a premium, zero organization is not a feature
