### ISSUE TITLE
Android: Backup file not being read by email applications

### ISSUE THREAD

**Issue by pshelly** [standardnotes/mobile#90]
When the decrypted backup file is requested, only gmail gets the attachment. **Outlook** and **K-9 Mail** don't receive  the attachment. 

Tested on Android 8.

**Comment by mobitar** [comment]
Sorry @pshelly, this is a known issue. We might need to transition to a file-based solution in the near future. Only the default email client is currently supported.

**Comment by mobitar** [comment]
Should be fixed in 3.0.0 release.
