### ISSUE TITLE
Round icon on Android

### ISSUE THREAD

**Issue by icstyle** [standardnotes/mobile#93]
Hi!

Please make the launcher icon round or, even better, adaptive for Android 8.0+. It's the only app that still has an ugly square icon :-).

Thanks

**Comment by mobitar** [comment]
Indeed, hope to work on this soon :)

**Comment by mobitar** [comment]
This is now available in v3.

**Comment by icstyle** [comment]
Looks great!

Am Di., 29. Jan. 2019 um 15:57 Uhr schrieb Mo Bitar <
notifications@github.com>:
