### ISSUE TITLE
Bug: scrolling of notes with plus editor doesn't work 

### ISSUE THREAD

**Issue by odyon01** [standardnotes/mobile#95]
With version 2.3.8 (wasn't sure if this is a beta release) on android, you can't normally scroll anymore through a note. It's very jumpy, half a line per swipe down. And you also switch very easy to the right and the normal editor shows up. 

Please fix this. It made standard notes basically unusable as I can't read some longer notes I have.

**Comment by mobitar** [comment]
The plus editor is notorious for its tricky scrolling due to having a frame within a frame. Not sure it was worsened recently, unless you are saying it's extra tricky now?

**Comment by odyon01** [comment]
Until I installed the latest SN version, I never had any problem with the Plus editor on Android. Even not with notes of 7+ A4 pages (when copied to Word) / 20k chars notes (which I frequently use and edit). I just noticed, scrolling only works when I move my finger super, super slowly down. But even then, it skips very easily to the side, enabling the new-swipe-to-the-side-feature. 

As I wrote, unfortunately, SN basically became almost unusable to me for the past week, and I have to create separate notes, until I can add them again together to the original, longer note. 

Can you reproduce this issue?

**Comment by mobitar** [comment]
Android version 2.3.10 should fix this issue (just released, give it about an hour to propagate).

**Comment by odyon01** [comment]
Great, thanks. Indeed solved now.
