### ISSUE TITLE
Android: Text duplication using spell checker with advanced markdown editor.

### ISSUE THREAD

**Issue by zedgoat** [standardnotes/mobile#97]
Standard notes v2.3.10
Android 7.1.2 (LineageOS version 14.1-20181011-NIGHTLY-hammerhead)
Default AOSP Keyboard.

Steps to reproduce:
- Create a new note
- Add enough content for the note to be scrollable.
- Select advanced markdown editor.
- Select the text so that it triggers the spell-check bar on the keyboard.
- Scroll the text window up and down.

The selected text will now duplicate, then be selected, and duplicate further. If you rapidly scrub the window up and down the text will continue to update after you stop interacting with the window.

Screenshot:

![2018-10-31 18 32 47](https://user-images.githubusercontent.com/19355901/47776665-aaea6900-dd3e-11e8-97ad-a7b6208de2e2.png)

**Comment by mobitar** [comment]
Hey @zedgoat, thanks for the detailed report. Is the duplication a UI issue, or does it also happen on the data side? Meaning, does the duplicated text actually save the note with that text, or is it only a visual misrepresentation?

**Comment by zedgoat** [comment]
@mobitar sorry should have noted, it's a content change. Looking at the way it runs it's almost like the document saves and triggers something with the spell checker, which triggers a save, then so on and so on when you are scrolling.

**Comment by mobitar** [comment]
Can you confirm whether this happens with any other editor, including the plain editor?

**Comment by zedgoat** [comment]
Can confirm it's limited to the advanced markdown editor. Plain and other editors do not have the duplication issue.

**Comment by bclouser** [comment]
+1 on this. It happens for me as well using the advanced markdown editor on android 8.1.0. Standard notes version 2.3.10

**Comment by mobitar** [comment]
Got it thanks, will need to investigate.

**Comment by Strayer** [comment]
This, or something similar, still happens in the current version 3 beta. As soon as I select text, something goes wrong. E.g., pressing the back key on the soft keyboard after selecting text duplicates the selected text. Sometimes I don't even have to select text, just pressing somewhere in the note to open the keyboard starts duplicating text under the cursor. I'm using the standard Google Keyboard installed on my Moto Z.

While correctable, this is very destructive for the notes :(

**Comment by mobitar** [comment]
This issue should now be fixed with Advanced Markdown Editor 1.2.6. Please clear cache on Android via the global Settings for this app if you don't see the fix right away.
